/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          *
 * Original Ada unit: Printer                                                *
 * Generation timestamp: 201412180740                                        *
 *****************************************************************************/

package printer.Printer;

/**
 * @origin printer.ads:1:9
 */
@SuppressWarnings("all")
public final class Printer_Package {

   /**
    * @origin printer.ads:3:14
    * @param Me is passed by value
    */
   static public void Print (printer.Standard.AdaString Me) {
      printer.Ada2Java.Library.lock.lock ();
      try {
         printer.Standard.AdaString Id_JNI_42 = Me;
         if (Id_JNI_42 == null) {
            throw new com.adacore.ajis.NativeException ("null not allowed for Me");
         }
         int [] Id_JNI_50;
         printer.Standard.AdaString Id_JNI_51 = Id_JNI_42;
         Id_JNI_50 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_51).getAccess ();
         Print_Id_JNI_39 (Id_JNI_50);
      } finally {
         printer.Ada2Java.Library.lock.unlock ();
      }
   } // Print

   native static private void Print_Id_JNI_39 (int [] Me);

   static {
      printer.Ada2Java.Library.load ();
   }

} // Printer_Package
