-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          --
-- Original Ada unit: Standard                                               --
-- Generation timestamp: 201501031502                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Ada.Unchecked_Deallocation;
with System.Address_To_Access_Conversions;
with Ada.Unchecked_Conversion;
with Ada.Tags;
with Ada.Exceptions;
with Interfaces.C;
with Interfaces.C.Strings;

package body JNI_Binding.Standard_JNI.AdaString_JNI is 

   procedure JNI_For_Body_Elaboration is begin null; end;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access) is
   begin

      null;
      AJIS.Internal.Java.Initialize (Id_JNI_45, Id_JNI_1);
   end Initialize_Unit_JNI;

   function Id_JNI_78 (Left : access constant Standard.String; Right : access constant Standard.String) return Standard.Boolean is
      Id_JNI_98 : Standard.Boolean := Standard."=" (Left.all, Right.all);
   begin
      return Id_JNI_98;
   end Id_JNI_78;

   function equals_Id_JNI_77 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Left : Interfaces.Java.JNI.J_Int_J_Array; Right : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Boolean is
   begin
      declare
         Id_JNI_80 : constant JNI_Binding.Standard_JNI.Id_JNI_47.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_47.To_Object_Pointer (Id_JNI_1, Left);
         Id_JNI_85 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_47.Get_Address (Id_JNI_80);
         subtype Id_JNI_81 is Standard.String (Id_JNI_80.Bound_1_Low .. Id_JNI_80.Bound_1_High);
         type Id_JNI_82 is access all Id_JNI_81;
         package Id_JNI_83 is new System.Address_To_Access_Conversions (Id_JNI_81);
         Id_JNI_84 : JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_80.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_84 := Id_JNI_83.To_Pointer (Id_JNI_85).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_80.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_84 := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer_Cst (Id_JNI_80.General_Pointer);
         else
            Id_JNI_84 := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer_Cst (Id_JNI_80.Constant_Pointer);
         end if;
         declare
            Id_JNI_89 : constant JNI_Binding.Standard_JNI.Id_JNI_47.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_47.To_Object_Pointer (Id_JNI_1, Right);
            Id_JNI_94 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_47.Get_Address (Id_JNI_89);
            subtype Id_JNI_90 is Standard.String (Id_JNI_89.Bound_1_Low .. Id_JNI_89.Bound_1_High);
            type Id_JNI_91 is access all Id_JNI_90;
            package Id_JNI_92 is new System.Address_To_Access_Conversions (Id_JNI_90);
            Id_JNI_93 : JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer_Cst;
         begin
            if AJIS.Internal.Java."=" (Id_JNI_89.Kind, AJIS.Internal.Java.Static) then
               Id_JNI_93 := Id_JNI_92.To_Pointer (Id_JNI_94).all'Unrestricted_Access;
            elsif AJIS.Internal.Java."=" (Id_JNI_89.Kind, AJIS.Internal.Java.General_Access) then
               Id_JNI_93 := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer_Cst (Id_JNI_89.General_Pointer);
            else
               Id_JNI_93 := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer_Cst (Id_JNI_89.Constant_Pointer);
            end if;
            declare
               Id_JNI_99 : Interfaces.Java.JNI.J_Boolean := Interfaces.Java.JNI.J_Boolean (Id_JNI_78 (Id_JNI_84, Id_JNI_93));
            begin
               return Id_JNI_99;
            end;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Boolean (False);
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Boolean (False);
         end;
   end equals_Id_JNI_77;

   function Id_JNI_105 (This : access Standard.String) return access Standard.String is
      Id_JNI_115 : JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer := new Standard.String'(This.all);
      Id_JNI_120 : JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer (Id_JNI_115);
   begin
      return Id_JNI_120;
   end Id_JNI_105;

   function internalClone_Id_JNI_104 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_107 : constant JNI_Binding.Standard_JNI.Id_JNI_47.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_47.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_112 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_47.Get_Address (Id_JNI_107);
         subtype Id_JNI_108 is Standard.String (Id_JNI_107.Bound_1_Low .. Id_JNI_107.Bound_1_High);
         type Id_JNI_109 is access all Id_JNI_108;
         package Id_JNI_110 is new System.Address_To_Access_Conversions (Id_JNI_108);
         Id_JNI_111 : JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_107.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_111 := Id_JNI_110.To_Pointer (Id_JNI_112).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_107.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_111 := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer (Id_JNI_107.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
            Id_JNI_117_Proxy : Interfaces.Java.JNI.J_Object;
            Id_JNI_118_Ptr : JNI_Binding.Standard_JNI.Id_JNI_47.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_47.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_47.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer (Id_JNI_105 (Id_JNI_111))));
         begin
            declare
               Id_JNI_121 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_47.To_J_Int_J_Array (Id_JNI_1, Id_JNI_118_Ptr);
            begin
               return Id_JNI_121;
            end;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end internalClone_Id_JNI_104;

   function Id_JNI_127 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; First_1 : Standard.Integer'Base; Last_1 : Standard.Integer'Base) return access Standard.String is
      Id_JNI_134 : JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer (JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer'( new Standard.String (First_1 .. Last_1)));
   begin
      return Id_JNI_134;
   end Id_JNI_127;

   function AdaString_Id_JNI_126 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; First_1 : Interfaces.Java.JNI.J_Int; Last_1 : Interfaces.Java.JNI.J_Int) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_131_Proxy : Interfaces.Java.JNI.J_Object;
         Id_JNI_132_Ptr : JNI_Binding.Standard_JNI.Id_JNI_47.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_47.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_47.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer (Id_JNI_127(Id_JNI_1, Id_JNI_2, Standard.Integer'Base (First_1), Standard.Integer'Base (Last_1)))));
      begin
         declare
            Id_JNI_135 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_47.To_J_Int_J_Array (Id_JNI_1, Id_JNI_132_Ptr);
         begin
            return Id_JNI_135;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end AdaString_Id_JNI_126;

   procedure Id_JNI_140 (Obj : access Standard.String) is
      Id_JNI_150 : JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer (Obj);
   begin
      JNI_Binding.Standard_JNI.Id_JNI_47.Free (Id_JNI_150);
   end Id_JNI_140;

   procedure deallocateNativeObject_Id_JNI_139 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Obj : Interfaces.Java.JNI.J_Int_J_Array) is
   begin
      declare
         Id_JNI_142 : constant JNI_Binding.Standard_JNI.Id_JNI_47.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_47.To_Object_Pointer (Id_JNI_1, Obj);
         Id_JNI_147 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_47.Get_Address (Id_JNI_142);
         subtype Id_JNI_143 is Standard.String (Id_JNI_142.Bound_1_Low .. Id_JNI_142.Bound_1_High);
         type Id_JNI_144 is access all Id_JNI_143;
         package Id_JNI_145 is new System.Address_To_Access_Conversions (Id_JNI_143);
         Id_JNI_146 : JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_142.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_146 := Id_JNI_145.To_Pointer (Id_JNI_147).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_142.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_146 := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer (Id_JNI_142.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
         begin
            Id_JNI_140 (Id_JNI_146);
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
         end;
   end deallocateNativeObject_Id_JNI_139;

   function Id_JNI_152 (This : access Standard.String; Index_1 : Standard.Integer'Base) return Standard.Character is
      Id_JNI_165 : Standard.Character := This (Index_1);
   begin
      return Id_JNI_165;
   end Id_JNI_152;

   function Get_Element_At_Id_JNI_151 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Index_1 : Interfaces.Java.JNI.J_Int) return Interfaces.Java.JNI.J_Char is
   begin
      declare
         Id_JNI_154 : constant JNI_Binding.Standard_JNI.Id_JNI_47.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_47.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_159 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_47.Get_Address (Id_JNI_154);
         subtype Id_JNI_155 is Standard.String (Id_JNI_154.Bound_1_Low .. Id_JNI_154.Bound_1_High);
         type Id_JNI_156 is access all Id_JNI_155;
         package Id_JNI_157 is new System.Address_To_Access_Conversions (Id_JNI_155);
         Id_JNI_158 : JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_154.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_158 := Id_JNI_157.To_Pointer (Id_JNI_159).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_154.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_158 := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer (Id_JNI_154.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
            Id_JNI_166 : Interfaces.Java.JNI.J_Char := Interfaces.Java.JNI.J_Char (Ada.Characters.Conversions.To_Wide_Character (Id_JNI_152 (Id_JNI_158, Standard.Integer'Base (Index_1))));
         begin
            return Id_JNI_166;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Char (Ada.Characters.Conversions.To_Wide_Character (ASCII.NUL));
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Char (Ada.Characters.Conversions.To_Wide_Character (ASCII.NUL));
         end;
   end Get_Element_At_Id_JNI_151;

   procedure Id_JNI_172 (This : access Standard.String; Index_1 : Standard.Integer'Base; Value : Standard.Character) is
   begin
      This (Index_1) := Value;
   end Id_JNI_172;

   procedure Set_Element_At_Id_JNI_171 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Index_1 : Interfaces.Java.JNI.J_Int; Value : Interfaces.Java.JNI.J_Char) is
   begin
      declare
         Id_JNI_174 : constant JNI_Binding.Standard_JNI.Id_JNI_47.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_47.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_179 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_47.Get_Address (Id_JNI_174);
         subtype Id_JNI_175 is Standard.String (Id_JNI_174.Bound_1_Low .. Id_JNI_174.Bound_1_High);
         type Id_JNI_176 is access all Id_JNI_175;
         package Id_JNI_177 is new System.Address_To_Access_Conversions (Id_JNI_175);
         Id_JNI_178 : JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_174.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_178 := Id_JNI_177.To_Pointer (Id_JNI_179).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_174.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_178 := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer (Id_JNI_174.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
         begin
            Id_JNI_172 (Id_JNI_178, Standard.Integer'Base (Index_1), Standard.Character (Ada.Characters.Conversions.To_Character (Wide_Character (Value))));
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
         end;
   end Set_Element_At_Id_JNI_171;

   function Id_JNI_185 (This : Standard.String) return Standard.Integer'Base is
      Id_JNI_196 : Standard.Integer'Base := This'First;
   begin
      return Id_JNI_196;
   end Id_JNI_185;

   function First_Id_JNI_184 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int is
   begin
      declare
         Id_JNI_187 : JNI_Binding.Standard_JNI.Id_JNI_47.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_47.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_192 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_47.Get_Address (Id_JNI_187);
         subtype Id_JNI_188 is Standard.String (Id_JNI_187.Bound_1_Low .. Id_JNI_187.Bound_1_High);
         type Id_JNI_189 is access all Id_JNI_188;
         package Id_JNI_190 is new System.Address_To_Access_Conversions (Id_JNI_188);
         Id_JNI_191 : JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_187.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_191 := Id_JNI_190.To_Pointer (Id_JNI_192).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_187.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_191 := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer_Cst (Id_JNI_187.General_Pointer);
         else
            Id_JNI_191 := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer_Cst (Id_JNI_187.Constant_Pointer);
         end if;
         declare
            Id_JNI_197 : Interfaces.Java.JNI.J_Int := Interfaces.Java.JNI.J_Int (Id_JNI_185 (Standard.String (Id_JNI_191.all)));
         begin
            return Id_JNI_197;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return 0;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return 0;
         end;
   end First_Id_JNI_184;

   function Id_JNI_203 (This : Standard.String) return Standard.Integer'Base is
      Id_JNI_214 : Standard.Integer'Base := This'Last;
   begin
      return Id_JNI_214;
   end Id_JNI_203;

   function Last_Id_JNI_202 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int is
   begin
      declare
         Id_JNI_205 : JNI_Binding.Standard_JNI.Id_JNI_47.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_47.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_210 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_47.Get_Address (Id_JNI_205);
         subtype Id_JNI_206 is Standard.String (Id_JNI_205.Bound_1_Low .. Id_JNI_205.Bound_1_High);
         type Id_JNI_207 is access all Id_JNI_206;
         package Id_JNI_208 is new System.Address_To_Access_Conversions (Id_JNI_206);
         Id_JNI_209 : JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_205.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_209 := Id_JNI_208.To_Pointer (Id_JNI_210).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_205.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_209 := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer_Cst (Id_JNI_205.General_Pointer);
         else
            Id_JNI_209 := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer_Cst (Id_JNI_205.Constant_Pointer);
         end if;
         declare
            Id_JNI_215 : Interfaces.Java.JNI.J_Int := Interfaces.Java.JNI.J_Int (Id_JNI_203 (Standard.String (Id_JNI_209.all)));
         begin
            return Id_JNI_215;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return 0;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return 0;
         end;
   end Last_Id_JNI_202;

   function Id_JNI_221 (This : Standard.String) return Standard.Integer is
      Id_JNI_232 : Standard.Integer := This'Length;
   begin
      return Id_JNI_232;
   end Id_JNI_221;

   function Length_Id_JNI_220 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int is
   begin
      declare
         Id_JNI_223 : JNI_Binding.Standard_JNI.Id_JNI_47.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_47.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_228 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_47.Get_Address (Id_JNI_223);
         subtype Id_JNI_224 is Standard.String (Id_JNI_223.Bound_1_Low .. Id_JNI_223.Bound_1_High);
         type Id_JNI_225 is access all Id_JNI_224;
         package Id_JNI_226 is new System.Address_To_Access_Conversions (Id_JNI_224);
         Id_JNI_227 : JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_223.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_227 := Id_JNI_226.To_Pointer (Id_JNI_228).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_223.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_227 := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer_Cst (Id_JNI_223.General_Pointer);
         else
            Id_JNI_227 := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer_Cst (Id_JNI_223.Constant_Pointer);
         end if;
         declare
            Id_JNI_233 : Interfaces.Java.JNI.J_Int := Interfaces.Java.JNI.J_Int (Id_JNI_221 (Standard.String (Id_JNI_227.all)));
         begin
            return Id_JNI_233;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return 0;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return 0;
         end;
   end Length_Id_JNI_220;

   function Id_JNI_239 return access Standard.String is
      Id_JNI_244 : JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer (JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer'(null));
   begin
      return Id_JNI_244;
   end Id_JNI_239;

   function createNullAccess_Id_JNI_238 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_3 : Interfaces.Java.JNI.J_Class) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_241_Proxy : Interfaces.Java.JNI.J_Object;
         Id_JNI_242_Ptr : JNI_Binding.Standard_JNI.Id_JNI_47.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_47.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_47.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer (Id_JNI_239)));
      begin
         declare
            Id_JNI_245 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_47.To_J_Int_J_Array (Id_JNI_1, Id_JNI_242_Ptr);
         begin
            return Id_JNI_245;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end createNullAccess_Id_JNI_238;

   function Id_JNI_251 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; This : Standard.String) return Interfaces.Java.JNI.J_String is
      Id_JNI_261 : Interfaces.C.Strings.chars_ptr;
      Id_JNI_262 : Interfaces.Java.JNI.J_String;
   begin
      Id_JNI_261 := Interfaces.C.Strings.New_String (String (This));
      Id_JNI_262 := Interfaces.Java.JNI.New_String_UTF (Id_JNI_1, Id_JNI_261);
      Interfaces.C.Strings.Free (Id_JNI_261);
      return Id_JNI_262;
   end Id_JNI_251;

   function toString_Id_JNI_250 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Object is
   begin
      declare
         Id_JNI_253 : JNI_Binding.Standard_JNI.Id_JNI_47.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_47.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_258 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_47.Get_Address (Id_JNI_253);
         subtype Id_JNI_254 is Standard.String (Id_JNI_253.Bound_1_Low .. Id_JNI_253.Bound_1_High);
         type Id_JNI_255 is access all Id_JNI_254;
         package Id_JNI_256 is new System.Address_To_Access_Conversions (Id_JNI_254);
         Id_JNI_257 : JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_253.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_257 := Id_JNI_256.To_Pointer (Id_JNI_258).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_253.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_257 := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer_Cst (Id_JNI_253.General_Pointer);
         else
            Id_JNI_257 := JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer_Cst (Id_JNI_253.Constant_Pointer);
         end if;
         declare
            Id_JNI_263 : Interfaces.Java.JNI.J_Object := Id_JNI_251 (Id_JNI_1, Standard.String (Id_JNI_257.all));
         begin
            return Id_JNI_263;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Object;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Object;
         end;
   end toString_Id_JNI_250;

   function Id_JNI_268 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Str : Interfaces.Java.JNI.J_String) return JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer is
      Is_Copy : aliased Interfaces.Java.JNI.J_Boolean;
      C_Str : constant Interfaces.C.Strings.chars_ptr := Interfaces.Java.JNI.Get_String_UTF_Chars (Id_JNI_1, Str, Is_Copy'Unchecked_Access);
      Ada_Str : constant AJIS.Internal.Java.Unchecked_String_Access := AJIS.Internal.Java.To_Unchecked_String (AJIS.Internal.Java.Convert (C_Str));
      pragma Suppress (Access_Check, Ada_Str);
      Result : JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer := new Standard.String'(Standard.String (Ada_Str (1 .. Integer (Interfaces.C.Strings.Strlen (C_Str)))));
   begin
      Interfaces.Java.JNI.Release_String_UTF_Chars (Id_JNI_1, Str, C_Str);
      return Result;
   end Id_JNI_268;

   function AdaString_Id_JNI_267 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Str : Interfaces.Java.JNI.J_Object) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_271_Proxy : Interfaces.Java.JNI.J_Object;
         Id_JNI_272_Ptr : JNI_Binding.Standard_JNI.Id_JNI_47.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_47.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_47.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer (Id_JNI_268(Id_JNI_1, Id_JNI_2, Str))));
      begin
         declare
            Id_JNI_274 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_47.To_J_Int_J_Array (Id_JNI_1, Id_JNI_272_Ptr);
         begin
            return Id_JNI_274;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end AdaString_Id_JNI_267;

begin
   null;
end JNI_Binding.Standard_JNI.AdaString_JNI;
