-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          --
-- Original Ada unit: JPrinter                                               --
-- Generation timestamp: 201501031502                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Interfaces.Java.JNI;
with AJIS;
with AJIS.Internal;
with AJIS.Java;
with AJIS.Internal.Java;
with Ada.Characters.Conversions;
with Ada.Finalization;
with JPrinter; use JPrinter;
with JNI_Binding.Standard_JNI;

package JNI_Binding.JPrinter_JNI.Print_CB_JNI is 

   procedure JNI_For_Body_Elaboration;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access);
   Id_JNI_42_Constructor : AJIS.Internal.Java.Java_Method_Access := AJIS.Internal.Java.Get_Java_Method ("jprinter/JPrinter/Id_JNI_42", "<init>", "(Lcom/adacore/ajis/internal/ada/AdaAccess;)V");

   generic
      Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access;
      Id_JNI_2 : Interfaces.Java.JNI.J_Object;
   procedure Print_CB (Str : Standard.String);

   procedure Print_CB_Body_Id_JNI_57_Callback (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Str : Interfaces.Java.JNI.J_Int_J_Array);
   Print_CB_Body_Id_JNI_57_Callback_Method_Access : AJIS.Internal.Java.Java_Method_Access := AJIS.Internal.Java.Get_Java_Method ("jprinter/JPrinter/Print_CB", "Print_CB_Body_Id_JNI_57_Callback", "([I)V");

end JNI_Binding.JPrinter_JNI.Print_CB_JNI;
