-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          --
-- Original Ada unit: JPrinter                                               --
-- Generation timestamp: 201501031502                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Interfaces.Java.JNI;
with AJIS;
with AJIS.Internal;
with AJIS.Java;
with AJIS.Internal.Java;
with Ada.Characters.Conversions;
with Ada.Finalization;
with JPrinter; use JPrinter;
with JNI_Binding.Standard_JNI;

package JNI_Binding.JPrinter_JNI.Id_JNI_42_JNI is 

   procedure JNI_For_Body_Elaboration;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access);

   procedure Id_JNI_64 (This : JPrinter.Print_CB; Str : Standard.String);

   procedure Print_CB_Body_Id_JNI_63 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Str : Interfaces.Java.JNI.J_Int_J_Array);
   pragma Export (C, Print_CB_Body_Id_JNI_63, "Java_jprinter_JPrinter_Id_1JNI_142_Print_1CB_1Body_1Id_1JNI_163___3I_3I");

end JNI_Binding.JPrinter_JNI.Id_JNI_42_JNI;
