-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          --
-- Original Ada unit: JPrinter                                               --
-- Generation timestamp: 201501031502                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Interfaces.Java.JNI;
with AJIS;
with AJIS.Internal;
with AJIS.Java;
with AJIS.Internal.Java;
with Ada.Characters.Conversions;
with Ada.Finalization;
with JPrinter; use JPrinter;
with JNI_Binding.Standard_JNI;

package JNI_Binding.JPrinter_JNI.JPrinter_Package_JNI is 

   procedure JNI_For_Body_Elaboration;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access);

   procedure Id_JNI_40 (Meth : JPrinter.Print_CB; Str : Standard.String);

   procedure Call_Back_Id_JNI_39 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_3 : Interfaces.Java.JNI.J_Class; Meth : Interfaces.Java.JNI.J_Object; Str : Interfaces.Java.JNI.J_Int_J_Array);
   pragma Export (C, Call_Back_Id_JNI_39, "Java_jprinter_JPrinter_JPrinter_1Package_Call_1Back_1Id_1JNI_139__Ljprinter_JPrinter_Print_1CB_2_3I");

end JNI_Binding.JPrinter_JNI.JPrinter_Package_JNI;
