-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          --
-- Original Ada unit: Standard                                               --
-- Generation timestamp: 201501031502                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Interfaces.Java.JNI;
with AJIS;
with AJIS.Internal;
with AJIS.Java;
with AJIS.Internal.Java;
with Ada.Characters.Conversions;
with Ada.Finalization;

package JNI_Binding.Standard_JNI.AdaString_JNI is 

   procedure JNI_For_Body_Elaboration;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access);

   function Id_JNI_78 (Left : access constant Standard.String; Right : access constant Standard.String) return Standard.Boolean;

   function equals_Id_JNI_77 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Left : Interfaces.Java.JNI.J_Int_J_Array; Right : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Boolean;
   pragma Export (C, equals_Id_JNI_77, "Java_jprinter_Standard_AdaString_equals_1Id_1JNI_177___3I_3I");

   function Id_JNI_105 (This : access Standard.String) return access Standard.String;

   function internalClone_Id_JNI_104 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int_J_Array;
   pragma Export (C, internalClone_Id_JNI_104, "Java_jprinter_Standard_AdaString_internalClone_1Id_1JNI_1104___3I");

   function Id_JNI_127 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; First_1 : Standard.Integer'Base; Last_1 : Standard.Integer'Base) return access Standard.String;

   function AdaString_Id_JNI_126 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; First_1 : Interfaces.Java.JNI.J_Int; Last_1 : Interfaces.Java.JNI.J_Int) return Interfaces.Java.JNI.J_Int_J_Array;
   pragma Export (C, AdaString_Id_JNI_126, "Java_jprinter_Standard_AdaString_AdaString_1Id_1JNI_1126__II");

   procedure Id_JNI_140 (Obj : access Standard.String);

   procedure deallocateNativeObject_Id_JNI_139 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Obj : Interfaces.Java.JNI.J_Int_J_Array);
   pragma Export (C, deallocateNativeObject_Id_JNI_139, "Java_jprinter_Standard_AdaString_deallocateNativeObject_1Id_1JNI_1139___3I");

   function Id_JNI_152 (This : access Standard.String; Index_1 : Standard.Integer'Base) return Standard.Character;

   function Get_Element_At_Id_JNI_151 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Index_1 : Interfaces.Java.JNI.J_Int) return Interfaces.Java.JNI.J_Char;
   pragma Export (C, Get_Element_At_Id_JNI_151, "Java_jprinter_Standard_AdaString_Get_1Element_1At_1Id_1JNI_1151___3II");

   procedure Id_JNI_172 (This : access Standard.String; Index_1 : Standard.Integer'Base; Value : Standard.Character);

   procedure Set_Element_At_Id_JNI_171 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Index_1 : Interfaces.Java.JNI.J_Int; Value : Interfaces.Java.JNI.J_Char);
   pragma Export (C, Set_Element_At_Id_JNI_171, "Java_jprinter_Standard_AdaString_Set_1Element_1At_1Id_1JNI_1171___3IIC");

   function Id_JNI_185 (This : Standard.String) return Standard.Integer'Base;

   function First_Id_JNI_184 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int;
   pragma Export (C, First_Id_JNI_184, "Java_jprinter_Standard_AdaString_First_1Id_1JNI_1184___3I");

   function Id_JNI_203 (This : Standard.String) return Standard.Integer'Base;

   function Last_Id_JNI_202 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int;
   pragma Export (C, Last_Id_JNI_202, "Java_jprinter_Standard_AdaString_Last_1Id_1JNI_1202___3I");

   function Id_JNI_221 (This : Standard.String) return Standard.Integer;

   function Length_Id_JNI_220 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int;
   pragma Export (C, Length_Id_JNI_220, "Java_jprinter_Standard_AdaString_Length_1Id_1JNI_1220___3I");

   function Id_JNI_239 return access Standard.String;

   function createNullAccess_Id_JNI_238 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_3 : Interfaces.Java.JNI.J_Class) return Interfaces.Java.JNI.J_Int_J_Array;
   pragma Export (C, createNullAccess_Id_JNI_238, "Java_jprinter_Standard_AdaString_createNullAccess_1Id_1JNI_1238__");

   function Id_JNI_251 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; This : Standard.String) return Interfaces.Java.JNI.J_String;

   function toString_Id_JNI_250 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Object;
   pragma Export (C, toString_Id_JNI_250, "Java_jprinter_Standard_AdaString_toString_1Id_1JNI_1250___3I");

   function Id_JNI_268 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Str : Interfaces.Java.JNI.J_String) return JNI_Binding.Standard_JNI.Id_JNI_47.Array_Pointer;

   function AdaString_Id_JNI_267 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Str : Interfaces.Java.JNI.J_Object) return Interfaces.Java.JNI.J_Int_J_Array;
   pragma Export (C, AdaString_Id_JNI_267, "Java_jprinter_Standard_AdaString_AdaString_1Id_1JNI_1267__Ljava_lang_String_2");

   Id_JNI_45 : AJIS.Internal.Java.Java_Method_Access := AJIS.Internal.Java.Get_Java_Method ("jprinter/Standard/AdaString", "<init>", "(Lcom/adacore/ajis/internal/ada/AdaAccess;)V");

end JNI_Binding.Standard_JNI.AdaString_JNI;
