/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          *
 * Original Ada unit: Q4                                                     *
 * Generation timestamp: 201412281256                                        *
 *****************************************************************************/

package quiz.Q4;

/**
 * @origin q4.ads:1:9
 */
@SuppressWarnings("all")
public final class Q4_Package {

   /**
    * @origin q4.ads:9:14
    * @param Obj is passed by reference (non escapable)
    */
   static public void Print_Target (quiz.Q4.Target Obj) {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_45;
         quiz.Q4.Target Id_JNI_46 = Obj;
         if (Id_JNI_46 == null) {
            Id_JNI_45 = com.adacore.ajis.internal.ada.AdaAccess.simpleNullAccess ();
         } else {
            Id_JNI_45 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_46).getAccess ();
         }
         Print_Target_Id_JNI_39 (Id_JNI_45);
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // Print_Target

   native static private void Print_Target_Id_JNI_39 (int [] Obj);

   static {
      quiz.Ada2Java.Library.load ();
   }

} // Q4_Package
