/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          *
 * Original Ada unit: Q4                                                     *
 * Generation timestamp: 201412281256                                        *
 *****************************************************************************/

package quiz.Q4;

/**
 * @origin q4.ads:3:9
 */
@SuppressWarnings("all")
public final class Target extends com.adacore.ajis.internal.ada.AdaProxy {

   /**
    * @origin q4.ads:3:9
    * @param this is passed by reference (non escapable)
    * @param Right is passed by reference (non escapable)
    */
   final public boolean equals (java.lang.Object Right) {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_51;
         java.lang.Object Id_JNI_52 = this;
         if (this.getClass () != Right.getClass ()) return false;
         if (Id_JNI_52 == null) {
            Id_JNI_51 = com.adacore.ajis.internal.ada.AdaAccess.simpleNullAccess ();
         } else {
            Id_JNI_51 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_52).getAccess ();
         }
         int [] Id_JNI_55;
         java.lang.Object Id_JNI_56 = ((com.adacore.ajis.internal.ada.AdaProxy) Right);
         if (Id_JNI_56 == null) {
            Id_JNI_55 = com.adacore.ajis.internal.ada.AdaAccess.simpleNullAccess ();
         } else {
            Id_JNI_55 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_56).getAccess ();
         }
         boolean Id_JNI_60 = equals_Id_JNI_47 (Id_JNI_51, Id_JNI_55);
         return Id_JNI_60;
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // equals

   /**
    * @origin q4.ads:3:9
    * @param this is passed by reference (non escapable)
    * @return is passed by reference (escapable)
    */
   public int [] internalClone () {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_68;
         quiz.Q4.Target Id_JNI_69 = this;
         if (Id_JNI_69 == null) {
            Id_JNI_68 = com.adacore.ajis.internal.ada.AdaAccess.simpleNullAccess ();
         } else {
            Id_JNI_68 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_69).getAccess ();
         }
         int [] Id_JNI_77 = ((int []) internalClone_Id_JNI_64 (Id_JNI_68));
         return Id_JNI_77;
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // internalClone

   /**
    * @origin q4.ads:3:9
    * @return is passed by reference (escapable)
    */
   public Target () {
      super (new com.adacore.ajis.internal.ada.AdaAccess (null));
      quiz.Ada2Java.Library.lock.lock ();
      try {
         this.adaAccess = Target_Id_JNI_81 ();
         this.myOwner = com.adacore.ajis.IProxy.Owner.PROXY;
         this.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // Target

   public Target (com.adacore.ajis.internal.ada.AdaAccess access) {
      this.adaAccess = access.fAcc;
   }

   /**
    * @origin q4.ads:3:9
    * @param this is passed by reference (non escapable)
    */
   public void deallocateNativeObject () {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_96;
         quiz.Q4.Target Id_JNI_97 = this;
         if (Id_JNI_97 == null) {
            Id_JNI_96 = com.adacore.ajis.internal.ada.AdaAccess.simpleNullAccess ();
         } else {
            Id_JNI_96 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_97).getAccess ();
         }
         deallocateNativeObject_Id_JNI_92 (Id_JNI_96);
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // deallocateNativeObject

   /**
    * @origin q4.ads:4:7
    * @param this is passed by reference (non escapable)
    */
   final public int Value () {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_103;
         quiz.Q4.Target Id_JNI_104 = this;
         if (Id_JNI_104 == null) {
            Id_JNI_103 = com.adacore.ajis.internal.ada.AdaAccess.simpleNullAccess ();
         } else {
            Id_JNI_103 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_104).getAccess ();
         }
         int Id_JNI_109 = Value_Id_JNI_99 (Id_JNI_103);
         return Id_JNI_109;
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // Value

   /**
    * @origin q4.ads:4:7
    * @param this is passed by reference (non escapable)
    */
   final public void Value (int Value) {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_117;
         quiz.Q4.Target Id_JNI_118 = this;
         if (Id_JNI_118 == null) {
            Id_JNI_117 = com.adacore.ajis.internal.ada.AdaAccess.simpleNullAccess ();
         } else {
            Id_JNI_117 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_118).getAccess ();
         }
         Value_Id_JNI_113 (Id_JNI_117, Value);
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // Value

   native private boolean equals_Id_JNI_47 (int [] Left, int [] Right);

   native private int [] internalClone_Id_JNI_64 (int [] This);

   native private int [] Target_Id_JNI_81 ();

   native private void deallocateNativeObject_Id_JNI_92 (int [] Obj);

   native private int Value_Id_JNI_99 (int [] This);

   native private void Value_Id_JNI_113 (int [] This, int Value);

   static {
      quiz.Ada2Java.Library.load ();
   }

} // Target
