/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          *
 * Original Ada unit: Ada2Java                                               *
 * Generation timestamp: 201412180740                                        *
 *****************************************************************************/

package printer.Ada2Java;

/**
 */
@SuppressWarnings("all")
public final class Library {
   public static final com.adacore.ajis.ILock lock = new com.adacore.ajis.DefaultLock ();
   private static boolean fLoaded = false;

   private static native void startLibrary ();

   public static void load () {
      if (!fLoaded) {
         fLoaded = true;
         com.adacore.ajis.AJISLibrary.load ();
         System.loadLibrary ("printer");
         startLibrary ();
      }
   }

   static {
      printer.Ada2Java.Library Id_JNI_324;
      printer.Ada.Exceptions.Exception_Occurrence Id_JNI_325;
      printer.Printer.Printer_Package Id_JNI_326;
      printer.Standard.AdaString Id_JNI_327;
      printer.Standard.Constraint_Error Id_JNI_328;
      printer.Standard.Program_Error Id_JNI_329;
      printer.Standard.Storage_Error Id_JNI_330;
   }

   static {
      printer.Ada2Java.Library.load ();
   }

} // Library
