-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          --
-- Original Ada unit: Ada2Java                                               --
-- Generation timestamp: 201412281256                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Ada.Unchecked_Deallocation;
with System.Address_To_Access_Conversions;
with Ada.Unchecked_Conversion;
with Ada.Tags;
with Ada.Exceptions;
with Interfaces.C;
with Interfaces.C.Strings;
with JNI_Binding;
with JNI_Binding.Ada2Java_JNI;
with JNI_Binding.Ada2Java_JNI.Library_JNI;
with JNI_Binding.Ada_JNI;
with JNI_Binding.Ada_JNI.Exceptions_JNI;
with JNI_Binding.Ada_JNI.Exceptions_JNI.Exception_Occurrence_JNI;
with JNI_Binding.Q4_JNI;
with JNI_Binding.Q4_JNI.Q4_Package_JNI;
with JNI_Binding.Q4_JNI.Target_JNI;
with JNI_Binding.Standard_JNI;
with JNI_Binding.Standard_JNI.AdaString_JNI;
with JNI_Binding.Standard_JNI.Constraint_Error_JNI;
with JNI_Binding.Standard_JNI.Program_Error_JNI;
with JNI_Binding.Standard_JNI.Storage_Error_JNI;

package body JNI_Binding.Ada2Java_JNI.Library_JNI is 

   procedure JNI_For_Body_Elaboration is begin null; end;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access) is
   begin

      null;
   end Initialize_Unit_JNI;

   procedure Load (Env : Interfaces.Java.JNI.JNI_Env_Access; Class : Interfaces.Java.JNI.J_Class);
   pragma Export (C, Load, "Java_quiz_Ada2Java_Library_startLibrary");

   procedure Load (Env : Interfaces.Java.JNI.JNI_Env_Access; Class : Interfaces.Java.JNI.J_Class) is
      procedure Internal;
      pragma Import (C, Internal, "quizinit");
   begin 
      Internal;
      Initialize_Library (Env);
   end Load;

   procedure Initialize_Library (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access) is
   begin
      AJIS.Internal.Java.Initialize_JNI (Id_JNI_1);
      JNI_Binding.Initialize_Unit_JNI (Id_JNI_1);
      JNI_Binding.Ada2Java_JNI.Initialize_Unit_JNI (Id_JNI_1);
      JNI_Binding.Ada2Java_JNI.Library_JNI.Initialize_Unit_JNI (Id_JNI_1);
      JNI_Binding.Ada_JNI.Initialize_Unit_JNI (Id_JNI_1);
      JNI_Binding.Ada_JNI.Exceptions_JNI.Initialize_Unit_JNI (Id_JNI_1);
      JNI_Binding.Ada_JNI.Exceptions_JNI.Exception_Occurrence_JNI.Initialize_Unit_JNI (Id_JNI_1);
      JNI_Binding.Q4_JNI.Initialize_Unit_JNI (Id_JNI_1);
      JNI_Binding.Q4_JNI.Q4_Package_JNI.Initialize_Unit_JNI (Id_JNI_1);
      JNI_Binding.Q4_JNI.Target_JNI.Initialize_Unit_JNI (Id_JNI_1);
      JNI_Binding.Standard_JNI.Initialize_Unit_JNI (Id_JNI_1);
      JNI_Binding.Standard_JNI.AdaString_JNI.Initialize_Unit_JNI (Id_JNI_1);
      JNI_Binding.Standard_JNI.Constraint_Error_JNI.Initialize_Unit_JNI (Id_JNI_1);
      JNI_Binding.Standard_JNI.Program_Error_JNI.Initialize_Unit_JNI (Id_JNI_1);
      JNI_Binding.Standard_JNI.Storage_Error_JNI.Initialize_Unit_JNI (Id_JNI_1);
   end Initialize_Library;

begin
   null;
end JNI_Binding.Ada2Java_JNI.Library_JNI;
