-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          --
-- Original Ada unit: Q4                                                     --
-- Generation timestamp: 201412281256                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Ada.Unchecked_Deallocation;
with System.Address_To_Access_Conversions;
with Ada.Unchecked_Conversion;
with Ada.Tags;
with Ada.Exceptions;
with Interfaces.C;
with Interfaces.C.Strings;

package body JNI_Binding.Q4_JNI.Target_JNI is 

   procedure JNI_For_Body_Elaboration is begin null; end;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access) is
   begin

      null;
      AJIS.Internal.Java.Initialize (Id_JNI_41, Id_JNI_1);
   end Initialize_Unit_JNI;

   function Id_JNI_48 (Left : access constant Q4.Target; Right : access constant Q4.Target) return Standard.Boolean is
      Id_JNI_58 : Standard.Boolean := Q4."=" (Left.all, Right.all);
   begin
      return Id_JNI_58;
   end Id_JNI_48;

   function equals_Id_JNI_47 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Left : Interfaces.Java.JNI.J_Int_J_Array; Right : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Boolean is
   begin
      declare
         Id_JNI_50 : JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer_Cst := JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer_Cst (JNI_Binding.Q4_JNI.Id_JNI_42.To_Pointer (Id_JNI_1, Left));
         Id_JNI_54 : JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer_Cst := JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer_Cst (JNI_Binding.Q4_JNI.Id_JNI_42.To_Pointer (Id_JNI_1, Right));
         Id_JNI_59 : Interfaces.Java.JNI.J_Boolean := Interfaces.Java.JNI.J_Boolean (Id_JNI_48 (Id_JNI_50, Id_JNI_54));
      begin
         return Id_JNI_59;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Boolean (False);
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Boolean (False);
         end;
   end equals_Id_JNI_47;

   function Id_JNI_65 (This : access Q4.Target) return access Q4.Target is
      Id_JNI_70 : JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer := new Q4.Target'(This.all);
      Id_JNI_75 : JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer := JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer (Id_JNI_70);
   begin
      return Id_JNI_75;
   end Id_JNI_65;

   function internalClone_Id_JNI_64 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_67 : JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer := JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer (JNI_Binding.Q4_JNI.Id_JNI_42.To_Pointer (Id_JNI_1, This));
         Id_JNI_72_Proxy : Interfaces.Java.JNI.J_Object;
         Id_JNI_73_Ptr : JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer := JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer (Id_JNI_65 (Id_JNI_67));
      begin
         declare
            Id_JNI_76 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Q4_JNI.Id_JNI_42.To_JintArray (Id_JNI_1, Id_JNI_73_Ptr);
         begin
            return Id_JNI_76;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end internalClone_Id_JNI_64;

   function Id_JNI_82 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object) return access Q4.Target is
      Id_JNI_87 : JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer := JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer (JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer'(new Q4.Target));
   begin
      return Id_JNI_87;
   end Id_JNI_82;

   function Target_Id_JNI_81 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_84_Proxy : Interfaces.Java.JNI.J_Object;
         Id_JNI_85_Ptr : JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer := JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer (Id_JNI_82(Id_JNI_1, Id_JNI_2));
      begin
         declare
            Id_JNI_88 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Q4_JNI.Id_JNI_42.To_JintArray (Id_JNI_1, Id_JNI_85_Ptr);
         begin
            return Id_JNI_88;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end Target_Id_JNI_81;

   procedure Id_JNI_93 (Obj : access Q4.Target) is
      Id_JNI_98 : JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer := JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer (Obj);
   begin
      JNI_Binding.Q4_JNI.Id_JNI_42.Free (Id_JNI_98);
   end Id_JNI_93;

   procedure deallocateNativeObject_Id_JNI_92 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Obj : Interfaces.Java.JNI.J_Int_J_Array) is
   begin
      declare
         Id_JNI_95 : JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer := JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer (JNI_Binding.Q4_JNI.Id_JNI_42.To_Pointer (Id_JNI_1, Obj));
      begin
         Id_JNI_93 (Id_JNI_95);
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
         end;
   end deallocateNativeObject_Id_JNI_92;

   function Id_JNI_100 (This : access Q4.Target) return Standard.Integer is
      Id_JNI_107 : Standard.Integer := This.Value;
   begin
      return Id_JNI_107;
   end Id_JNI_100;

   function Value_Id_JNI_99 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int is
   begin
      declare
         Id_JNI_102 : JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer := JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer (JNI_Binding.Q4_JNI.Id_JNI_42.To_Pointer (Id_JNI_1, This));
         Id_JNI_108 : Interfaces.Java.JNI.J_Int := Interfaces.Java.JNI.J_Int (Id_JNI_100 (Id_JNI_102));
      begin
         return Id_JNI_108;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return 0;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return 0;
         end;
   end Value_Id_JNI_99;

   procedure Id_JNI_114 (This : access Q4.Target; Value : Standard.Integer) is
   begin
      This.Value := Value;
   end Id_JNI_114;

   procedure Value_Id_JNI_113 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Value : Interfaces.Java.JNI.J_Int) is
   begin
      declare
         Id_JNI_116 : JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer := JNI_Binding.Q4_JNI.Id_JNI_42.Object_Pointer (JNI_Binding.Q4_JNI.Id_JNI_42.To_Pointer (Id_JNI_1, This));
      begin
         Id_JNI_114 (Id_JNI_116, Standard.Integer (Value));
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
         end;
   end Value_Id_JNI_113;

begin
   null;
end JNI_Binding.Q4_JNI.Target_JNI;
