-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          --
-- Original Ada unit: Standard                                               --
-- Generation timestamp: 201412281256                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Ada.Unchecked_Deallocation;
with System.Address_To_Access_Conversions;
with Ada.Unchecked_Conversion;
with Ada.Tags;
with Ada.Exceptions;
with Interfaces.C;
with Interfaces.C.Strings;

package body JNI_Binding.Standard_JNI.AdaString_JNI is 

   procedure JNI_For_Body_Elaboration is begin null; end;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access) is
   begin

      null;
      AJIS.Internal.Java.Initialize (Id_JNI_121, Id_JNI_1);
   end Initialize_Unit_JNI;

   function Id_JNI_124 (Left : access constant Standard.String; Right : access constant Standard.String) return Standard.Boolean is
      Id_JNI_144 : Standard.Boolean := Standard."=" (Left.all, Right.all);
   begin
      return Id_JNI_144;
   end Id_JNI_124;

   function equals_Id_JNI_123 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Left : Interfaces.Java.JNI.J_Int_J_Array; Right : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Boolean is
   begin
      declare
         Id_JNI_126 : constant JNI_Binding.Standard_JNI.Id_JNI_122.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_122.To_Object_Pointer (Id_JNI_1, Left);
         Id_JNI_131 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_122.Get_Address (Id_JNI_126);
         subtype Id_JNI_127 is Standard.String (Id_JNI_126.Bound_1_Low .. Id_JNI_126.Bound_1_High);
         type Id_JNI_128 is access all Id_JNI_127;
         package Id_JNI_129 is new System.Address_To_Access_Conversions (Id_JNI_127);
         Id_JNI_130 : JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_126.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_130 := Id_JNI_129.To_Pointer (Id_JNI_131).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_126.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_130 := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer_Cst (Id_JNI_126.General_Pointer);
         else
            Id_JNI_130 := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer_Cst (Id_JNI_126.Constant_Pointer);
         end if;
         declare
            Id_JNI_135 : constant JNI_Binding.Standard_JNI.Id_JNI_122.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_122.To_Object_Pointer (Id_JNI_1, Right);
            Id_JNI_140 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_122.Get_Address (Id_JNI_135);
            subtype Id_JNI_136 is Standard.String (Id_JNI_135.Bound_1_Low .. Id_JNI_135.Bound_1_High);
            type Id_JNI_137 is access all Id_JNI_136;
            package Id_JNI_138 is new System.Address_To_Access_Conversions (Id_JNI_136);
            Id_JNI_139 : JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer_Cst;
         begin
            if AJIS.Internal.Java."=" (Id_JNI_135.Kind, AJIS.Internal.Java.Static) then
               Id_JNI_139 := Id_JNI_138.To_Pointer (Id_JNI_140).all'Unrestricted_Access;
            elsif AJIS.Internal.Java."=" (Id_JNI_135.Kind, AJIS.Internal.Java.General_Access) then
               Id_JNI_139 := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer_Cst (Id_JNI_135.General_Pointer);
            else
               Id_JNI_139 := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer_Cst (Id_JNI_135.Constant_Pointer);
            end if;
            declare
               Id_JNI_145 : Interfaces.Java.JNI.J_Boolean := Interfaces.Java.JNI.J_Boolean (Id_JNI_124 (Id_JNI_130, Id_JNI_139));
            begin
               return Id_JNI_145;
            end;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Boolean (False);
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Boolean (False);
         end;
   end equals_Id_JNI_123;

   function Id_JNI_151 (This : access Standard.String) return access Standard.String is
      Id_JNI_161 : JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer := new Standard.String'(This.all);
      Id_JNI_166 : JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer (Id_JNI_161);
   begin
      return Id_JNI_166;
   end Id_JNI_151;

   function internalClone_Id_JNI_150 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_153 : constant JNI_Binding.Standard_JNI.Id_JNI_122.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_122.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_158 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_122.Get_Address (Id_JNI_153);
         subtype Id_JNI_154 is Standard.String (Id_JNI_153.Bound_1_Low .. Id_JNI_153.Bound_1_High);
         type Id_JNI_155 is access all Id_JNI_154;
         package Id_JNI_156 is new System.Address_To_Access_Conversions (Id_JNI_154);
         Id_JNI_157 : JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_153.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_157 := Id_JNI_156.To_Pointer (Id_JNI_158).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_153.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_157 := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer (Id_JNI_153.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
            Id_JNI_163_Proxy : Interfaces.Java.JNI.J_Object;
            Id_JNI_164_Ptr : JNI_Binding.Standard_JNI.Id_JNI_122.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_122.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_122.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer (Id_JNI_151 (Id_JNI_157))));
         begin
            declare
               Id_JNI_167 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_122.To_J_Int_J_Array (Id_JNI_1, Id_JNI_164_Ptr);
            begin
               return Id_JNI_167;
            end;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end internalClone_Id_JNI_150;

   function Id_JNI_173 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; First_1 : Standard.Integer'Base; Last_1 : Standard.Integer'Base) return access Standard.String is
      Id_JNI_180 : JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer (JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer'( new Standard.String (First_1 .. Last_1)));
   begin
      return Id_JNI_180;
   end Id_JNI_173;

   function AdaString_Id_JNI_172 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; First_1 : Interfaces.Java.JNI.J_Int; Last_1 : Interfaces.Java.JNI.J_Int) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_177_Proxy : Interfaces.Java.JNI.J_Object;
         Id_JNI_178_Ptr : JNI_Binding.Standard_JNI.Id_JNI_122.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_122.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_122.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer (Id_JNI_173(Id_JNI_1, Id_JNI_2, Standard.Integer'Base (First_1), Standard.Integer'Base (Last_1)))));
      begin
         declare
            Id_JNI_181 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_122.To_J_Int_J_Array (Id_JNI_1, Id_JNI_178_Ptr);
         begin
            return Id_JNI_181;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end AdaString_Id_JNI_172;

   procedure Id_JNI_186 (Obj : access Standard.String) is
      Id_JNI_196 : JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer (Obj);
   begin
      JNI_Binding.Standard_JNI.Id_JNI_122.Free (Id_JNI_196);
   end Id_JNI_186;

   procedure deallocateNativeObject_Id_JNI_185 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Obj : Interfaces.Java.JNI.J_Int_J_Array) is
   begin
      declare
         Id_JNI_188 : constant JNI_Binding.Standard_JNI.Id_JNI_122.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_122.To_Object_Pointer (Id_JNI_1, Obj);
         Id_JNI_193 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_122.Get_Address (Id_JNI_188);
         subtype Id_JNI_189 is Standard.String (Id_JNI_188.Bound_1_Low .. Id_JNI_188.Bound_1_High);
         type Id_JNI_190 is access all Id_JNI_189;
         package Id_JNI_191 is new System.Address_To_Access_Conversions (Id_JNI_189);
         Id_JNI_192 : JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_188.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_192 := Id_JNI_191.To_Pointer (Id_JNI_193).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_188.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_192 := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer (Id_JNI_188.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
         begin
            Id_JNI_186 (Id_JNI_192);
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
         end;
   end deallocateNativeObject_Id_JNI_185;

   function Id_JNI_198 (This : access Standard.String; Index_1 : Standard.Integer'Base) return Standard.Character is
      Id_JNI_211 : Standard.Character := This (Index_1);
   begin
      return Id_JNI_211;
   end Id_JNI_198;

   function Get_Element_At_Id_JNI_197 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Index_1 : Interfaces.Java.JNI.J_Int) return Interfaces.Java.JNI.J_Char is
   begin
      declare
         Id_JNI_200 : constant JNI_Binding.Standard_JNI.Id_JNI_122.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_122.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_205 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_122.Get_Address (Id_JNI_200);
         subtype Id_JNI_201 is Standard.String (Id_JNI_200.Bound_1_Low .. Id_JNI_200.Bound_1_High);
         type Id_JNI_202 is access all Id_JNI_201;
         package Id_JNI_203 is new System.Address_To_Access_Conversions (Id_JNI_201);
         Id_JNI_204 : JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_200.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_204 := Id_JNI_203.To_Pointer (Id_JNI_205).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_200.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_204 := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer (Id_JNI_200.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
            Id_JNI_212 : Interfaces.Java.JNI.J_Char := Interfaces.Java.JNI.J_Char (Ada.Characters.Conversions.To_Wide_Character (Id_JNI_198 (Id_JNI_204, Standard.Integer'Base (Index_1))));
         begin
            return Id_JNI_212;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Char (Ada.Characters.Conversions.To_Wide_Character (ASCII.NUL));
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Char (Ada.Characters.Conversions.To_Wide_Character (ASCII.NUL));
         end;
   end Get_Element_At_Id_JNI_197;

   procedure Id_JNI_218 (This : access Standard.String; Index_1 : Standard.Integer'Base; Value : Standard.Character) is
   begin
      This (Index_1) := Value;
   end Id_JNI_218;

   procedure Set_Element_At_Id_JNI_217 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Index_1 : Interfaces.Java.JNI.J_Int; Value : Interfaces.Java.JNI.J_Char) is
   begin
      declare
         Id_JNI_220 : constant JNI_Binding.Standard_JNI.Id_JNI_122.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_122.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_225 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_122.Get_Address (Id_JNI_220);
         subtype Id_JNI_221 is Standard.String (Id_JNI_220.Bound_1_Low .. Id_JNI_220.Bound_1_High);
         type Id_JNI_222 is access all Id_JNI_221;
         package Id_JNI_223 is new System.Address_To_Access_Conversions (Id_JNI_221);
         Id_JNI_224 : JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_220.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_224 := Id_JNI_223.To_Pointer (Id_JNI_225).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_220.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_224 := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer (Id_JNI_220.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
         begin
            Id_JNI_218 (Id_JNI_224, Standard.Integer'Base (Index_1), Standard.Character (Ada.Characters.Conversions.To_Character (Wide_Character (Value))));
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
         end;
   end Set_Element_At_Id_JNI_217;

   function Id_JNI_231 (This : Standard.String) return Standard.Integer'Base is
      Id_JNI_242 : Standard.Integer'Base := This'First;
   begin
      return Id_JNI_242;
   end Id_JNI_231;

   function First_Id_JNI_230 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int is
   begin
      declare
         Id_JNI_233 : JNI_Binding.Standard_JNI.Id_JNI_122.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_122.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_238 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_122.Get_Address (Id_JNI_233);
         subtype Id_JNI_234 is Standard.String (Id_JNI_233.Bound_1_Low .. Id_JNI_233.Bound_1_High);
         type Id_JNI_235 is access all Id_JNI_234;
         package Id_JNI_236 is new System.Address_To_Access_Conversions (Id_JNI_234);
         Id_JNI_237 : JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_233.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_237 := Id_JNI_236.To_Pointer (Id_JNI_238).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_233.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_237 := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer_Cst (Id_JNI_233.General_Pointer);
         else
            Id_JNI_237 := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer_Cst (Id_JNI_233.Constant_Pointer);
         end if;
         declare
            Id_JNI_243 : Interfaces.Java.JNI.J_Int := Interfaces.Java.JNI.J_Int (Id_JNI_231 (Standard.String (Id_JNI_237.all)));
         begin
            return Id_JNI_243;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return 0;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return 0;
         end;
   end First_Id_JNI_230;

   function Id_JNI_249 (This : Standard.String) return Standard.Integer'Base is
      Id_JNI_260 : Standard.Integer'Base := This'Last;
   begin
      return Id_JNI_260;
   end Id_JNI_249;

   function Last_Id_JNI_248 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int is
   begin
      declare
         Id_JNI_251 : JNI_Binding.Standard_JNI.Id_JNI_122.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_122.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_256 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_122.Get_Address (Id_JNI_251);
         subtype Id_JNI_252 is Standard.String (Id_JNI_251.Bound_1_Low .. Id_JNI_251.Bound_1_High);
         type Id_JNI_253 is access all Id_JNI_252;
         package Id_JNI_254 is new System.Address_To_Access_Conversions (Id_JNI_252);
         Id_JNI_255 : JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_251.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_255 := Id_JNI_254.To_Pointer (Id_JNI_256).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_251.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_255 := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer_Cst (Id_JNI_251.General_Pointer);
         else
            Id_JNI_255 := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer_Cst (Id_JNI_251.Constant_Pointer);
         end if;
         declare
            Id_JNI_261 : Interfaces.Java.JNI.J_Int := Interfaces.Java.JNI.J_Int (Id_JNI_249 (Standard.String (Id_JNI_255.all)));
         begin
            return Id_JNI_261;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return 0;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return 0;
         end;
   end Last_Id_JNI_248;

   function Id_JNI_267 (This : Standard.String) return Standard.Integer is
      Id_JNI_278 : Standard.Integer := This'Length;
   begin
      return Id_JNI_278;
   end Id_JNI_267;

   function Length_Id_JNI_266 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int is
   begin
      declare
         Id_JNI_269 : JNI_Binding.Standard_JNI.Id_JNI_122.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_122.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_274 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_122.Get_Address (Id_JNI_269);
         subtype Id_JNI_270 is Standard.String (Id_JNI_269.Bound_1_Low .. Id_JNI_269.Bound_1_High);
         type Id_JNI_271 is access all Id_JNI_270;
         package Id_JNI_272 is new System.Address_To_Access_Conversions (Id_JNI_270);
         Id_JNI_273 : JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_269.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_273 := Id_JNI_272.To_Pointer (Id_JNI_274).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_269.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_273 := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer_Cst (Id_JNI_269.General_Pointer);
         else
            Id_JNI_273 := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer_Cst (Id_JNI_269.Constant_Pointer);
         end if;
         declare
            Id_JNI_279 : Interfaces.Java.JNI.J_Int := Interfaces.Java.JNI.J_Int (Id_JNI_267 (Standard.String (Id_JNI_273.all)));
         begin
            return Id_JNI_279;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return 0;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return 0;
         end;
   end Length_Id_JNI_266;

   function Id_JNI_285 return access Standard.String is
      Id_JNI_290 : JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer (JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer'(null));
   begin
      return Id_JNI_290;
   end Id_JNI_285;

   function createNullAccess_Id_JNI_284 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_3 : Interfaces.Java.JNI.J_Class) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_287_Proxy : Interfaces.Java.JNI.J_Object;
         Id_JNI_288_Ptr : JNI_Binding.Standard_JNI.Id_JNI_122.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_122.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_122.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer (Id_JNI_285)));
      begin
         declare
            Id_JNI_291 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_122.To_J_Int_J_Array (Id_JNI_1, Id_JNI_288_Ptr);
         begin
            return Id_JNI_291;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end createNullAccess_Id_JNI_284;

   function Id_JNI_297 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; This : Standard.String) return Interfaces.Java.JNI.J_String is
      Id_JNI_307 : Interfaces.C.Strings.chars_ptr;
      Id_JNI_308 : Interfaces.Java.JNI.J_String;
   begin
      Id_JNI_307 := Interfaces.C.Strings.New_String (String (This));
      Id_JNI_308 := Interfaces.Java.JNI.New_String_UTF (Id_JNI_1, Id_JNI_307);
      Interfaces.C.Strings.Free (Id_JNI_307);
      return Id_JNI_308;
   end Id_JNI_297;

   function toString_Id_JNI_296 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Object is
   begin
      declare
         Id_JNI_299 : JNI_Binding.Standard_JNI.Id_JNI_122.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_122.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_304 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_122.Get_Address (Id_JNI_299);
         subtype Id_JNI_300 is Standard.String (Id_JNI_299.Bound_1_Low .. Id_JNI_299.Bound_1_High);
         type Id_JNI_301 is access all Id_JNI_300;
         package Id_JNI_302 is new System.Address_To_Access_Conversions (Id_JNI_300);
         Id_JNI_303 : JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_299.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_303 := Id_JNI_302.To_Pointer (Id_JNI_304).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_299.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_303 := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer_Cst (Id_JNI_299.General_Pointer);
         else
            Id_JNI_303 := JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer_Cst (Id_JNI_299.Constant_Pointer);
         end if;
         declare
            Id_JNI_309 : Interfaces.Java.JNI.J_Object := Id_JNI_297 (Id_JNI_1, Standard.String (Id_JNI_303.all));
         begin
            return Id_JNI_309;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Object;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Object;
         end;
   end toString_Id_JNI_296;

   function Id_JNI_314 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Str : Interfaces.Java.JNI.J_String) return JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer is
      Is_Copy : aliased Interfaces.Java.JNI.J_Boolean;
      C_Str : constant Interfaces.C.Strings.chars_ptr := Interfaces.Java.JNI.Get_String_UTF_Chars (Id_JNI_1, Str, Is_Copy'Unchecked_Access);
      Ada_Str : constant AJIS.Internal.Java.Unchecked_String_Access := AJIS.Internal.Java.To_Unchecked_String (AJIS.Internal.Java.Convert (C_Str));
      pragma Suppress (Access_Check, Ada_Str);
      Result : JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer := new Standard.String'(Standard.String (Ada_Str (1 .. Integer (Interfaces.C.Strings.Strlen (C_Str)))));
   begin
      Interfaces.Java.JNI.Release_String_UTF_Chars (Id_JNI_1, Str, C_Str);
      return Result;
   end Id_JNI_314;

   function AdaString_Id_JNI_313 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Str : Interfaces.Java.JNI.J_Object) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_317_Proxy : Interfaces.Java.JNI.J_Object;
         Id_JNI_318_Ptr : JNI_Binding.Standard_JNI.Id_JNI_122.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_122.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_122.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_122.Array_Pointer (Id_JNI_314(Id_JNI_1, Id_JNI_2, Str))));
      begin
         declare
            Id_JNI_320 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_122.To_J_Int_J_Array (Id_JNI_1, Id_JNI_318_Ptr);
         begin
            return Id_JNI_320;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end AdaString_Id_JNI_313;

begin
   null;
end JNI_Binding.Standard_JNI.AdaString_JNI;
