-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          --
-- Original Ada unit: Q4                                                     --
-- Generation timestamp: 201412281256                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Interfaces.Java.JNI;
with AJIS;
with AJIS.Internal;
with AJIS.Java;
with AJIS.Internal.Java;
with Ada.Characters.Conversions;
with Ada.Finalization;
with Q4; use Q4;
with JNI_Binding.Q4_JNI;
with Q4;

package JNI_Binding.Q4_JNI.Q4_Package_JNI is 

   procedure JNI_For_Body_Elaboration;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access);

   procedure Id_JNI_40 (Obj : Q4.Access_Target);

   procedure Print_Target_Id_JNI_39 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_3 : Interfaces.Java.JNI.J_Class; Obj : Interfaces.Java.JNI.J_Int_J_Array);
   pragma Export (C, Print_Target_Id_JNI_39, "Java_quiz_Q4_Q4_1Package_Print_1Target_1Id_1JNI_139___3I");

end JNI_Binding.Q4_JNI.Q4_Package_JNI;
