-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          --
-- Original Ada unit: Q4                                                     --
-- Generation timestamp: 201412281256                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Interfaces.Java.JNI;
with AJIS;
with AJIS.Internal;
with AJIS.Java;
with AJIS.Internal.Java;
with Ada.Characters.Conversions;
with Ada.Finalization;
with Q4; use Q4;
with Q4;

package JNI_Binding.Q4_JNI.Target_JNI is 

   procedure JNI_For_Body_Elaboration;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access);

   function Id_JNI_48 (Left : access constant Q4.Target; Right : access constant Q4.Target) return Standard.Boolean;

   function equals_Id_JNI_47 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Left : Interfaces.Java.JNI.J_Int_J_Array; Right : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Boolean;
   pragma Export (C, equals_Id_JNI_47, "Java_quiz_Q4_Target_equals_1Id_1JNI_147___3I_3I");

   function Id_JNI_65 (This : access Q4.Target) return access Q4.Target;

   function internalClone_Id_JNI_64 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int_J_Array;
   pragma Export (C, internalClone_Id_JNI_64, "Java_quiz_Q4_Target_internalClone_1Id_1JNI_164___3I");

   function Id_JNI_82 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object) return access Q4.Target;

   function Target_Id_JNI_81 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object) return Interfaces.Java.JNI.J_Int_J_Array;
   pragma Export (C, Target_Id_JNI_81, "Java_quiz_Q4_Target_Target_1Id_1JNI_181__");

   procedure Id_JNI_93 (Obj : access Q4.Target);

   procedure deallocateNativeObject_Id_JNI_92 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Obj : Interfaces.Java.JNI.J_Int_J_Array);
   pragma Export (C, deallocateNativeObject_Id_JNI_92, "Java_quiz_Q4_Target_deallocateNativeObject_1Id_1JNI_192___3I");

   function Id_JNI_100 (This : access Q4.Target) return Standard.Integer;

   function Value_Id_JNI_99 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int;
   pragma Export (C, Value_Id_JNI_99, "Java_quiz_Q4_Target_Value_1Id_1JNI_199___3I");

   procedure Id_JNI_114 (This : access Q4.Target; Value : Standard.Integer);

   procedure Value_Id_JNI_113 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Value : Interfaces.Java.JNI.J_Int);
   pragma Export (C, Value_Id_JNI_113, "Java_quiz_Q4_Target_Value_1Id_1JNI_1113___3II");

   Id_JNI_41 : AJIS.Internal.Java.Java_Method_Access := AJIS.Internal.Java.Get_Java_Method ("quiz/Q4/Target", "<init>", "(Lcom/adacore/ajis/internal/ada/AdaAccess;)V");

end JNI_Binding.Q4_JNI.Target_JNI;
