-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          --
-- Original Ada unit: Ada.Exceptions                                         --
-- Generation timestamp: 201412180740                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Ada.Unchecked_Deallocation;
with System.Address_To_Access_Conversions;
with Ada.Unchecked_Conversion;
with Ada.Tags;
with Ada.Exceptions;
with Interfaces.C;
with Interfaces.C.Strings;

package body JNI_Binding.Ada_JNI.Exceptions_JNI.Exception_Occurrence_JNI is 

   procedure JNI_For_Body_Elaboration is begin null; end;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access) is
   begin

      null;
      AJIS.Internal.Java.Initialize (Id_JNI_4, Id_JNI_1);
   end Initialize_Unit_JNI;

   function Id_JNI_22 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object) return access Ada.Exceptions.Exception_Occurrence is
      Id_JNI_27 : JNI_Binding.Ada_JNI.Exceptions_JNI.Id_JNI_5.Object_Pointer := JNI_Binding.Ada_JNI.Exceptions_JNI.Id_JNI_5.Object_Pointer (JNI_Binding.Ada_JNI.Exceptions_JNI.Id_JNI_5.Object_Pointer'(new Ada.Exceptions.Exception_Occurrence));
   begin
      return Id_JNI_27;
   end Id_JNI_22;

   function Exception_Occurrence_Id_JNI_21 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_24_Proxy : Interfaces.Java.JNI.J_Object;
         Id_JNI_25_Ptr : JNI_Binding.Ada_JNI.Exceptions_JNI.Id_JNI_5.Object_Pointer := JNI_Binding.Ada_JNI.Exceptions_JNI.Id_JNI_5.Object_Pointer (Id_JNI_22(Id_JNI_1, Id_JNI_2));
      begin
         declare
            Id_JNI_28 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Ada_JNI.Exceptions_JNI.Id_JNI_5.To_JintArray (Id_JNI_1, Id_JNI_25_Ptr);
         begin
            return Id_JNI_28;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end Exception_Occurrence_Id_JNI_21;

   procedure Id_JNI_33 (Obj : access Ada.Exceptions.Exception_Occurrence) is
      Id_JNI_38 : JNI_Binding.Ada_JNI.Exceptions_JNI.Id_JNI_5.Object_Pointer := JNI_Binding.Ada_JNI.Exceptions_JNI.Id_JNI_5.Object_Pointer (Obj);
   begin
      JNI_Binding.Ada_JNI.Exceptions_JNI.Id_JNI_5.Free (Id_JNI_38);
   end Id_JNI_33;

   procedure deallocateNativeObject_Id_JNI_32 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Obj : Interfaces.Java.JNI.J_Int_J_Array) is
   begin
      declare
         Id_JNI_35 : JNI_Binding.Ada_JNI.Exceptions_JNI.Id_JNI_5.Object_Pointer := JNI_Binding.Ada_JNI.Exceptions_JNI.Id_JNI_5.Object_Pointer (JNI_Binding.Ada_JNI.Exceptions_JNI.Id_JNI_5.To_Pointer (Id_JNI_1, Obj));
      begin
         Id_JNI_33 (Id_JNI_35);
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
         end;
   end deallocateNativeObject_Id_JNI_32;

begin
   null;
end JNI_Binding.Ada_JNI.Exceptions_JNI.Exception_Occurrence_JNI;
