-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          --
-- Original Ada unit: Ada.Exceptions                                         --
-- Generation timestamp: 201412180740                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Interfaces.Java.JNI;
with AJIS;
with AJIS.Internal;
with AJIS.Java;
with AJIS.Internal.Java;
with Ada.Characters.Conversions;
with Ada.Finalization;
with Ada; use Ada;
with Ada.Exceptions; use Ada.Exceptions;
with Ada.Exceptions;

package JNI_Binding.Ada_JNI.Exceptions_JNI.Exception_Occurrence_JNI is 

   procedure JNI_For_Body_Elaboration;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access);

   function Id_JNI_22 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object) return access Ada.Exceptions.Exception_Occurrence;

   function Exception_Occurrence_Id_JNI_21 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object) return Interfaces.Java.JNI.J_Int_J_Array;
   pragma Export (C, Exception_Occurrence_Id_JNI_21, "Java_printer_Ada_Exceptions_Exception_1Occurrence_Exception_1Occurrence_1Id_1JNI_121__");

   procedure Id_JNI_33 (Obj : access Ada.Exceptions.Exception_Occurrence);

   procedure deallocateNativeObject_Id_JNI_32 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Obj : Interfaces.Java.JNI.J_Int_J_Array);
   pragma Export (C, deallocateNativeObject_Id_JNI_32, "Java_printer_Ada_Exceptions_Exception_1Occurrence_deallocateNativeObject_1Id_1JNI_132___3I");

   Id_JNI_4 : AJIS.Internal.Java.Java_Method_Access := AJIS.Internal.Java.Get_Java_Method ("printer/Ada/Exceptions/Exception_Occurrence", "<init>", "(Lcom/adacore/ajis/internal/ada/AdaAccess;)V");

end JNI_Binding.Ada_JNI.Exceptions_JNI.Exception_Occurrence_JNI;
