-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          --
-- Original Ada unit: Standard                                               --
-- Generation timestamp: 201412180740                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Ada.Unchecked_Deallocation;
with System.Address_To_Access_Conversions;
with Ada.Unchecked_Conversion;
with Ada.Tags;
with Ada.Exceptions;
with Interfaces.C;
with Interfaces.C.Strings;

package body JNI_Binding.Standard_JNI.AdaString_JNI is 

   procedure JNI_For_Body_Elaboration is begin null; end;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access) is
   begin

      null;
      AJIS.Internal.Java.Initialize (Id_JNI_41, Id_JNI_1);
   end Initialize_Unit_JNI;

   function Id_JNI_53 (Left : access constant Standard.String; Right : access constant Standard.String) return Standard.Boolean is
      Id_JNI_73 : Standard.Boolean := Standard."=" (Left.all, Right.all);
   begin
      return Id_JNI_73;
   end Id_JNI_53;

   function equals_Id_JNI_52 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Left : Interfaces.Java.JNI.J_Int_J_Array; Right : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Boolean is
   begin
      declare
         Id_JNI_55 : constant JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, Left);
         Id_JNI_60 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_55);
         subtype Id_JNI_56 is Standard.String (Id_JNI_55.Bound_1_Low .. Id_JNI_55.Bound_1_High);
         type Id_JNI_57 is access all Id_JNI_56;
         package Id_JNI_58 is new System.Address_To_Access_Conversions (Id_JNI_56);
         Id_JNI_59 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_55.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_59 := Id_JNI_58.To_Pointer (Id_JNI_60).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_55.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_59 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_55.General_Pointer);
         else
            Id_JNI_59 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_55.Constant_Pointer);
         end if;
         declare
            Id_JNI_64 : constant JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, Right);
            Id_JNI_69 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_64);
            subtype Id_JNI_65 is Standard.String (Id_JNI_64.Bound_1_Low .. Id_JNI_64.Bound_1_High);
            type Id_JNI_66 is access all Id_JNI_65;
            package Id_JNI_67 is new System.Address_To_Access_Conversions (Id_JNI_65);
            Id_JNI_68 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst;
         begin
            if AJIS.Internal.Java."=" (Id_JNI_64.Kind, AJIS.Internal.Java.Static) then
               Id_JNI_68 := Id_JNI_67.To_Pointer (Id_JNI_69).all'Unrestricted_Access;
            elsif AJIS.Internal.Java."=" (Id_JNI_64.Kind, AJIS.Internal.Java.General_Access) then
               Id_JNI_68 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_64.General_Pointer);
            else
               Id_JNI_68 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_64.Constant_Pointer);
            end if;
            declare
               Id_JNI_74 : Interfaces.Java.JNI.J_Boolean := Interfaces.Java.JNI.J_Boolean (Id_JNI_53 (Id_JNI_59, Id_JNI_68));
            begin
               return Id_JNI_74;
            end;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Boolean (False);
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Boolean (False);
         end;
   end equals_Id_JNI_52;

   function Id_JNI_80 (This : access Standard.String) return access Standard.String is
      Id_JNI_90 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer := new Standard.String'(This.all);
      Id_JNI_95 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Id_JNI_90);
   begin
      return Id_JNI_95;
   end Id_JNI_80;

   function internalClone_Id_JNI_79 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_82 : constant JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_87 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_82);
         subtype Id_JNI_83 is Standard.String (Id_JNI_82.Bound_1_Low .. Id_JNI_82.Bound_1_High);
         type Id_JNI_84 is access all Id_JNI_83;
         package Id_JNI_85 is new System.Address_To_Access_Conversions (Id_JNI_83);
         Id_JNI_86 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_82.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_86 := Id_JNI_85.To_Pointer (Id_JNI_87).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_82.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_86 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Id_JNI_82.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
            Id_JNI_92_Proxy : Interfaces.Java.JNI.J_Object;
            Id_JNI_93_Ptr : JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_43.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Id_JNI_80 (Id_JNI_86))));
         begin
            declare
               Id_JNI_96 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_43.To_J_Int_J_Array (Id_JNI_1, Id_JNI_93_Ptr);
            begin
               return Id_JNI_96;
            end;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end internalClone_Id_JNI_79;

   function Id_JNI_102 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; First_1 : Standard.Integer'Base; Last_1 : Standard.Integer'Base) return access Standard.String is
      Id_JNI_109 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer'( new Standard.String (First_1 .. Last_1)));
   begin
      return Id_JNI_109;
   end Id_JNI_102;

   function AdaString_Id_JNI_101 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; First_1 : Interfaces.Java.JNI.J_Int; Last_1 : Interfaces.Java.JNI.J_Int) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_106_Proxy : Interfaces.Java.JNI.J_Object;
         Id_JNI_107_Ptr : JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_43.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Id_JNI_102(Id_JNI_1, Id_JNI_2, Standard.Integer'Base (First_1), Standard.Integer'Base (Last_1)))));
      begin
         declare
            Id_JNI_110 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_43.To_J_Int_J_Array (Id_JNI_1, Id_JNI_107_Ptr);
         begin
            return Id_JNI_110;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end AdaString_Id_JNI_101;

   procedure Id_JNI_115 (Obj : access Standard.String) is
      Id_JNI_125 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Obj);
   begin
      JNI_Binding.Standard_JNI.Id_JNI_43.Free (Id_JNI_125);
   end Id_JNI_115;

   procedure deallocateNativeObject_Id_JNI_114 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Obj : Interfaces.Java.JNI.J_Int_J_Array) is
   begin
      declare
         Id_JNI_117 : constant JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, Obj);
         Id_JNI_122 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_117);
         subtype Id_JNI_118 is Standard.String (Id_JNI_117.Bound_1_Low .. Id_JNI_117.Bound_1_High);
         type Id_JNI_119 is access all Id_JNI_118;
         package Id_JNI_120 is new System.Address_To_Access_Conversions (Id_JNI_118);
         Id_JNI_121 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_117.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_121 := Id_JNI_120.To_Pointer (Id_JNI_122).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_117.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_121 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Id_JNI_117.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
         begin
            Id_JNI_115 (Id_JNI_121);
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
         end;
   end deallocateNativeObject_Id_JNI_114;

   function Id_JNI_127 (This : access Standard.String; Index_1 : Standard.Integer'Base) return Standard.Character is
      Id_JNI_140 : Standard.Character := This (Index_1);
   begin
      return Id_JNI_140;
   end Id_JNI_127;

   function Get_Element_At_Id_JNI_126 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Index_1 : Interfaces.Java.JNI.J_Int) return Interfaces.Java.JNI.J_Char is
   begin
      declare
         Id_JNI_129 : constant JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_134 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_129);
         subtype Id_JNI_130 is Standard.String (Id_JNI_129.Bound_1_Low .. Id_JNI_129.Bound_1_High);
         type Id_JNI_131 is access all Id_JNI_130;
         package Id_JNI_132 is new System.Address_To_Access_Conversions (Id_JNI_130);
         Id_JNI_133 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_129.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_133 := Id_JNI_132.To_Pointer (Id_JNI_134).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_129.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_133 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Id_JNI_129.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
            Id_JNI_141 : Interfaces.Java.JNI.J_Char := Interfaces.Java.JNI.J_Char (Ada.Characters.Conversions.To_Wide_Character (Id_JNI_127 (Id_JNI_133, Standard.Integer'Base (Index_1))));
         begin
            return Id_JNI_141;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Char (Ada.Characters.Conversions.To_Wide_Character (ASCII.NUL));
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Char (Ada.Characters.Conversions.To_Wide_Character (ASCII.NUL));
         end;
   end Get_Element_At_Id_JNI_126;

   procedure Id_JNI_147 (This : access Standard.String; Index_1 : Standard.Integer'Base; Value : Standard.Character) is
   begin
      This (Index_1) := Value;
   end Id_JNI_147;

   procedure Set_Element_At_Id_JNI_146 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Index_1 : Interfaces.Java.JNI.J_Int; Value : Interfaces.Java.JNI.J_Char) is
   begin
      declare
         Id_JNI_149 : constant JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_154 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_149);
         subtype Id_JNI_150 is Standard.String (Id_JNI_149.Bound_1_Low .. Id_JNI_149.Bound_1_High);
         type Id_JNI_151 is access all Id_JNI_150;
         package Id_JNI_152 is new System.Address_To_Access_Conversions (Id_JNI_150);
         Id_JNI_153 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_149.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_153 := Id_JNI_152.To_Pointer (Id_JNI_154).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_149.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_153 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Id_JNI_149.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
         begin
            Id_JNI_147 (Id_JNI_153, Standard.Integer'Base (Index_1), Standard.Character (Ada.Characters.Conversions.To_Character (Wide_Character (Value))));
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
         end;
   end Set_Element_At_Id_JNI_146;

   function Id_JNI_160 (This : Standard.String) return Standard.Integer'Base is
      Id_JNI_171 : Standard.Integer'Base := This'First;
   begin
      return Id_JNI_171;
   end Id_JNI_160;

   function First_Id_JNI_159 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int is
   begin
      declare
         Id_JNI_162 : JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_167 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_162);
         subtype Id_JNI_163 is Standard.String (Id_JNI_162.Bound_1_Low .. Id_JNI_162.Bound_1_High);
         type Id_JNI_164 is access all Id_JNI_163;
         package Id_JNI_165 is new System.Address_To_Access_Conversions (Id_JNI_163);
         Id_JNI_166 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_162.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_166 := Id_JNI_165.To_Pointer (Id_JNI_167).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_162.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_166 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_162.General_Pointer);
         else
            Id_JNI_166 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_162.Constant_Pointer);
         end if;
         declare
            Id_JNI_172 : Interfaces.Java.JNI.J_Int := Interfaces.Java.JNI.J_Int (Id_JNI_160 (Standard.String (Id_JNI_166.all)));
         begin
            return Id_JNI_172;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return 0;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return 0;
         end;
   end First_Id_JNI_159;

   function Id_JNI_178 (This : Standard.String) return Standard.Integer'Base is
      Id_JNI_189 : Standard.Integer'Base := This'Last;
   begin
      return Id_JNI_189;
   end Id_JNI_178;

   function Last_Id_JNI_177 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int is
   begin
      declare
         Id_JNI_180 : JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_185 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_180);
         subtype Id_JNI_181 is Standard.String (Id_JNI_180.Bound_1_Low .. Id_JNI_180.Bound_1_High);
         type Id_JNI_182 is access all Id_JNI_181;
         package Id_JNI_183 is new System.Address_To_Access_Conversions (Id_JNI_181);
         Id_JNI_184 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_180.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_184 := Id_JNI_183.To_Pointer (Id_JNI_185).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_180.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_184 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_180.General_Pointer);
         else
            Id_JNI_184 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_180.Constant_Pointer);
         end if;
         declare
            Id_JNI_190 : Interfaces.Java.JNI.J_Int := Interfaces.Java.JNI.J_Int (Id_JNI_178 (Standard.String (Id_JNI_184.all)));
         begin
            return Id_JNI_190;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return 0;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return 0;
         end;
   end Last_Id_JNI_177;

   function Id_JNI_196 (This : Standard.String) return Standard.Integer is
      Id_JNI_207 : Standard.Integer := This'Length;
   begin
      return Id_JNI_207;
   end Id_JNI_196;

   function Length_Id_JNI_195 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int is
   begin
      declare
         Id_JNI_198 : JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_203 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_198);
         subtype Id_JNI_199 is Standard.String (Id_JNI_198.Bound_1_Low .. Id_JNI_198.Bound_1_High);
         type Id_JNI_200 is access all Id_JNI_199;
         package Id_JNI_201 is new System.Address_To_Access_Conversions (Id_JNI_199);
         Id_JNI_202 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_198.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_202 := Id_JNI_201.To_Pointer (Id_JNI_203).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_198.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_202 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_198.General_Pointer);
         else
            Id_JNI_202 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_198.Constant_Pointer);
         end if;
         declare
            Id_JNI_208 : Interfaces.Java.JNI.J_Int := Interfaces.Java.JNI.J_Int (Id_JNI_196 (Standard.String (Id_JNI_202.all)));
         begin
            return Id_JNI_208;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return 0;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return 0;
         end;
   end Length_Id_JNI_195;

   function Id_JNI_214 return access Standard.String is
      Id_JNI_219 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer'(null));
   begin
      return Id_JNI_219;
   end Id_JNI_214;

   function createNullAccess_Id_JNI_213 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_3 : Interfaces.Java.JNI.J_Class) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_216_Proxy : Interfaces.Java.JNI.J_Object;
         Id_JNI_217_Ptr : JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_43.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Id_JNI_214)));
      begin
         declare
            Id_JNI_220 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_43.To_J_Int_J_Array (Id_JNI_1, Id_JNI_217_Ptr);
         begin
            return Id_JNI_220;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end createNullAccess_Id_JNI_213;

   function Id_JNI_226 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; This : Standard.String) return Interfaces.Java.JNI.J_String is
      Id_JNI_236 : Interfaces.C.Strings.chars_ptr;
      Id_JNI_237 : Interfaces.Java.JNI.J_String;
   begin
      Id_JNI_236 := Interfaces.C.Strings.New_String (String (This));
      Id_JNI_237 := Interfaces.Java.JNI.New_String_UTF (Id_JNI_1, Id_JNI_236);
      Interfaces.C.Strings.Free (Id_JNI_236);
      return Id_JNI_237;
   end Id_JNI_226;

   function toString_Id_JNI_225 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Object is
   begin
      declare
         Id_JNI_228 : JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_233 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_228);
         subtype Id_JNI_229 is Standard.String (Id_JNI_228.Bound_1_Low .. Id_JNI_228.Bound_1_High);
         type Id_JNI_230 is access all Id_JNI_229;
         package Id_JNI_231 is new System.Address_To_Access_Conversions (Id_JNI_229);
         Id_JNI_232 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_228.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_232 := Id_JNI_231.To_Pointer (Id_JNI_233).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_228.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_232 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_228.General_Pointer);
         else
            Id_JNI_232 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_228.Constant_Pointer);
         end if;
         declare
            Id_JNI_238 : Interfaces.Java.JNI.J_Object := Id_JNI_226 (Id_JNI_1, Standard.String (Id_JNI_232.all));
         begin
            return Id_JNI_238;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Object;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Object;
         end;
   end toString_Id_JNI_225;

   function Id_JNI_243 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Str : Interfaces.Java.JNI.J_String) return JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer is
      Is_Copy : aliased Interfaces.Java.JNI.J_Boolean;
      C_Str : constant Interfaces.C.Strings.chars_ptr := Interfaces.Java.JNI.Get_String_UTF_Chars (Id_JNI_1, Str, Is_Copy'Unchecked_Access);
      Ada_Str : constant AJIS.Internal.Java.Unchecked_String_Access := AJIS.Internal.Java.To_Unchecked_String (AJIS.Internal.Java.Convert (C_Str));
      pragma Suppress (Access_Check, Ada_Str);
      Result : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer := new Standard.String'(Standard.String (Ada_Str (1 .. Integer (Interfaces.C.Strings.Strlen (C_Str)))));
   begin
      Interfaces.Java.JNI.Release_String_UTF_Chars (Id_JNI_1, Str, C_Str);
      return Result;
   end Id_JNI_243;

   function AdaString_Id_JNI_242 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Str : Interfaces.Java.JNI.J_Object) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_246_Proxy : Interfaces.Java.JNI.J_Object;
         Id_JNI_247_Ptr : JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_43.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Id_JNI_243(Id_JNI_1, Id_JNI_2, Str))));
      begin
         declare
            Id_JNI_249 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_43.To_J_Int_J_Array (Id_JNI_1, Id_JNI_247_Ptr);
         begin
            return Id_JNI_249;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end AdaString_Id_JNI_242;

begin
   null;
end JNI_Binding.Standard_JNI.AdaString_JNI;
