-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          --
-- Original Ada unit: Printer                                                --
-- Generation timestamp: 201412180740                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Interfaces.Java.JNI;
with AJIS;
with AJIS.Internal;
with AJIS.Java;
with AJIS.Internal.Java;
with Ada.Characters.Conversions;
with Ada.Finalization;
with Printer; use Printer;
with JNI_Binding.Standard_JNI;

package JNI_Binding.Printer_JNI.Printer_Package_JNI is 

   procedure JNI_For_Body_Elaboration;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access);

   procedure Id_JNI_40 (Me : Standard.String);

   procedure Print_Id_JNI_39 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_3 : Interfaces.Java.JNI.J_Class; Me : Interfaces.Java.JNI.J_Int_J_Array);
   pragma Export (C, Print_Id_JNI_39, "Java_printer_Printer_Printer_1Package_Print_1Id_1JNI_139___3I");

end JNI_Binding.Printer_JNI.Printer_Package_JNI;
