/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          *
 * Original Ada unit: Standard                                               *
 * Generation timestamp: 201412281256                                        *
 *****************************************************************************/

package quiz.Standard;

/**
 */
@SuppressWarnings("all")
public final class AdaString extends com.adacore.ajis.internal.ada.AdaProxy {

   /**
    * @param this is passed by reference (non escapable)
    * @param Right is passed by reference (non escapable)
    */
   final public boolean equals (java.lang.Object Right) {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_132;
         java.lang.Object Id_JNI_133 = this;
         if (this.getClass () != Right.getClass ()) return false;
         if (Id_JNI_133 == null) {
            Id_JNI_132 = quiz.Standard.AdaString.nullArrayAccess ();
         } else {
            Id_JNI_132 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_133).getAccess ();
         }
         int [] Id_JNI_141;
         java.lang.Object Id_JNI_142 = ((com.adacore.ajis.internal.ada.AdaProxy) Right);
         if (Id_JNI_142 == null) {
            Id_JNI_141 = quiz.Standard.AdaString.nullArrayAccess ();
         } else {
            Id_JNI_141 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_142).getAccess ();
         }
         boolean Id_JNI_146 = equals_Id_JNI_123 (Id_JNI_132, Id_JNI_141);
         return Id_JNI_146;
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // equals

   /**
    * @param this is passed by reference (non escapable)
    * @return is passed by reference (escapable)
    */
   public int [] internalClone () {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_159;
         quiz.Standard.AdaString Id_JNI_160 = this;
         if (Id_JNI_160 == null) {
            Id_JNI_159 = quiz.Standard.AdaString.nullArrayAccess ();
         } else {
            Id_JNI_159 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_160).getAccess ();
         }
         int [] Id_JNI_168 = ((int []) internalClone_Id_JNI_150 (Id_JNI_159));
         return Id_JNI_168;
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // internalClone

   /**
    * @return is passed by reference (escapable)
    */
   public AdaString (int First_1, int Last_1) {
      super (new com.adacore.ajis.internal.ada.AdaAccess (null));
      quiz.Ada2Java.Library.lock.lock ();
      try {
         this.adaAccess = AdaString_Id_JNI_172 (First_1, Last_1);
         this.myOwner = com.adacore.ajis.IProxy.Owner.PROXY;
         this.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // AdaString

   public AdaString (com.adacore.ajis.internal.ada.AdaAccess access) {
      this.adaAccess = access.fAcc;
   }

   /**
    * @param this is passed by reference (non escapable)
    */
   public void deallocateNativeObject () {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_194;
         quiz.Standard.AdaString Id_JNI_195 = this;
         if (Id_JNI_195 == null) {
            Id_JNI_194 = quiz.Standard.AdaString.nullArrayAccess ();
         } else {
            Id_JNI_194 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_195).getAccess ();
         }
         deallocateNativeObject_Id_JNI_185 (Id_JNI_194);
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // deallocateNativeObject

   /**
    * @param this is passed by reference (non escapable)
    */
   final public char Get_Element_At (int Index_1) {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_206;
         quiz.Standard.AdaString Id_JNI_207 = this;
         if (Id_JNI_207 == null) {
            Id_JNI_206 = quiz.Standard.AdaString.nullArrayAccess ();
         } else {
            Id_JNI_206 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_207).getAccess ();
         }
         char Id_JNI_213 = Get_Element_At_Id_JNI_197 (Id_JNI_206, Index_1);
         return Id_JNI_213;
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // Get_Element_At

   /**
    * @param this is passed by reference (non escapable)
    */
   final public void Set_Element_At (int Index_1, char Value) {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_226;
         quiz.Standard.AdaString Id_JNI_227 = this;
         if (Id_JNI_227 == null) {
            Id_JNI_226 = quiz.Standard.AdaString.nullArrayAccess ();
         } else {
            Id_JNI_226 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_227).getAccess ();
         }
         Set_Element_At_Id_JNI_217 (Id_JNI_226, Index_1, Value);
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // Set_Element_At

   /**
    * @param this is passed by value
    */
   final public int First () {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_239;
         quiz.Standard.AdaString Id_JNI_240 = this;
         Id_JNI_239 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_240).getAccess ();
         int Id_JNI_244 = First_Id_JNI_230 (Id_JNI_239);
         return Id_JNI_244;
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // First

   /**
    * @param this is passed by value
    */
   final public int Last () {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_257;
         quiz.Standard.AdaString Id_JNI_258 = this;
         Id_JNI_257 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_258).getAccess ();
         int Id_JNI_262 = Last_Id_JNI_248 (Id_JNI_257);
         return Id_JNI_262;
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // Last

   /**
    * @param this is passed by value
    */
   final public int Length () {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_275;
         quiz.Standard.AdaString Id_JNI_276 = this;
         Id_JNI_275 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_276).getAccess ();
         int Id_JNI_280 = Length_Id_JNI_266 (Id_JNI_275);
         return Id_JNI_280;
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // Length

   /**
    * @return is passed by reference (escapable)
    */
   static public int [] createNullAccess () {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_292 = ((int []) createNullAccess_Id_JNI_284 ());
         return Id_JNI_292;
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // createNullAccess

   private static int [] nullArrayAccessVal;

   public static int [] nullArrayAccess () {
      if (nullArrayAccessVal == null) {
         nullArrayAccessVal = createNullAccess ();
      }
      return nullArrayAccessVal;
   }

   /**
    * @param this is passed by value
    * @return is passed by value
    */
   final public java.lang.String toString () {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_305;
         quiz.Standard.AdaString Id_JNI_306 = this;
         Id_JNI_305 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_306).getAccess ();
         java.lang.String Id_JNI_310 = toString_Id_JNI_296 (Id_JNI_305);
         return Id_JNI_310;
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // toString

   /**
    * @param Str is passed by value
    * @return is passed by reference (escapable)
    */
   public AdaString (java.lang.String Str) {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         java.lang.String Id_JNI_315 = Str;
         if (Id_JNI_315 == null) {
            throw new com.adacore.ajis.NativeException ("null not allowed for Str");
         }
         this.adaAccess = AdaString_Id_JNI_313 (Id_JNI_315);
         this.myOwner = com.adacore.ajis.IProxy.Owner.PROXY;
         this.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // AdaString

   native private boolean equals_Id_JNI_123 (int [] Left, int [] Right);

   native private int [] internalClone_Id_JNI_150 (int [] This);

   native private int [] AdaString_Id_JNI_172 (int First_1, int Last_1);

   native private void deallocateNativeObject_Id_JNI_185 (int [] Obj);

   native private char Get_Element_At_Id_JNI_197 (int [] This, int Index_1);

   native private void Set_Element_At_Id_JNI_217 (int [] This, int Index_1, char Value);

   native private int First_Id_JNI_230 (int [] This);

   native private int Last_Id_JNI_248 (int [] This);

   native private int Length_Id_JNI_266 (int [] This);

   native static private int [] createNullAccess_Id_JNI_284 ();

   native private java.lang.String toString_Id_JNI_296 (int [] This);

   native private int [] AdaString_Id_JNI_313 (java.lang.String Str);

   static {
      quiz.Ada2Java.Library.load ();
   }

} // AdaString
