/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          *
 * Original Ada unit: Standard                                               *
 * Generation timestamp: 201412281256                                        *
 *****************************************************************************/

package quiz.Standard;

/**
 */
@SuppressWarnings("all")
public final class Program_Error extends com.adacore.ajis.NativeException implements com.adacore.ajis.internal.ada.AdaException {

   quiz.Ada.Exceptions.Exception_Occurrence Id_JNI_347;

   private Program_Error (String message, int [] addr) {
      super (message);
      Id_JNI_347 = new quiz.Ada.Exceptions.Exception_Occurrence (new com.adacore.ajis.internal.ada.AdaAccess (addr));
      Id_JNI_347.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
      Id_JNI_347.myOwner = com.adacore.ajis.IProxy.Owner.PROXY;
   }

   public Program_Error (quiz.Standard.AdaString message) {
      super (message.toString());
      Id_JNI_347 = createOccurrence (message);
   }

   public int [] getExceptionAddr () {
      return Id_JNI_347.getAccess ();
   }

   /**
    * @param Message is passed by value
    * @return is passed by reference (escapable)
    */
   static public quiz.Ada.Exceptions.Exception_Occurrence createOccurrence (quiz.Standard.AdaString Message) {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         quiz.Standard.AdaString Id_JNI_350 = Message;
         if (Id_JNI_350 == null) {
            throw new com.adacore.ajis.NativeException ("null not allowed for Message");
         }
         int [] Id_JNI_357;
         quiz.Standard.AdaString Id_JNI_358 = Id_JNI_350;
         Id_JNI_357 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_358).getAccess ();
         int [] Id_JNI_363 = createOccurrence_Id_JNI_348 (Id_JNI_357);
         quiz.Ada.Exceptions.Exception_Occurrence Id_JNI_364;
         if (com.adacore.ajis.internal.ada.AdaAccess.isNull (Id_JNI_363)) {
            Id_JNI_364 = null;
         } else {
            Id_JNI_364 = new quiz.Ada.Exceptions.Exception_Occurrence (new com.adacore.ajis.internal.ada.AdaAccess (Id_JNI_363));
         }
         quiz.Ada.Exceptions.Exception_Occurrence Id_JNI_365 = Id_JNI_364;
         if (Id_JNI_365 != null) {
            Id_JNI_365.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
         }
         quiz.Ada.Exceptions.Exception_Occurrence Id_JNI_368 = Id_JNI_365;
         return Id_JNI_368;
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // createOccurrence

   native static private int [] createOccurrence_Id_JNI_348 (int [] Message);

   static {
      quiz.Ada2Java.Library.load ();
   }

} // Program_Error
