/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          *
 * Original Ada unit: Standard                                               *
 * Generation timestamp: 201412281256                                        *
 *****************************************************************************/

package quiz.Standard;

/**
 */
@SuppressWarnings("all")
public final class Storage_Error extends com.adacore.ajis.NativeException implements com.adacore.ajis.internal.ada.AdaException {

   quiz.Ada.Exceptions.Exception_Occurrence Id_JNI_371;

   private Storage_Error (String message, int [] addr) {
      super (message);
      Id_JNI_371 = new quiz.Ada.Exceptions.Exception_Occurrence (new com.adacore.ajis.internal.ada.AdaAccess (addr));
      Id_JNI_371.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
      Id_JNI_371.myOwner = com.adacore.ajis.IProxy.Owner.PROXY;
   }

   public Storage_Error (quiz.Standard.AdaString message) {
      super (message.toString());
      Id_JNI_371 = createOccurrence (message);
   }

   public int [] getExceptionAddr () {
      return Id_JNI_371.getAccess ();
   }

   /**
    * @param Message is passed by value
    * @return is passed by reference (escapable)
    */
   static public quiz.Ada.Exceptions.Exception_Occurrence createOccurrence (quiz.Standard.AdaString Message) {
      quiz.Ada2Java.Library.lock.lock ();
      try {
         quiz.Standard.AdaString Id_JNI_374 = Message;
         if (Id_JNI_374 == null) {
            throw new com.adacore.ajis.NativeException ("null not allowed for Message");
         }
         int [] Id_JNI_381;
         quiz.Standard.AdaString Id_JNI_382 = Id_JNI_374;
         Id_JNI_381 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_382).getAccess ();
         int [] Id_JNI_387 = createOccurrence_Id_JNI_372 (Id_JNI_381);
         quiz.Ada.Exceptions.Exception_Occurrence Id_JNI_388;
         if (com.adacore.ajis.internal.ada.AdaAccess.isNull (Id_JNI_387)) {
            Id_JNI_388 = null;
         } else {
            Id_JNI_388 = new quiz.Ada.Exceptions.Exception_Occurrence (new com.adacore.ajis.internal.ada.AdaAccess (Id_JNI_387));
         }
         quiz.Ada.Exceptions.Exception_Occurrence Id_JNI_389 = Id_JNI_388;
         if (Id_JNI_389 != null) {
            Id_JNI_389.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
         }
         quiz.Ada.Exceptions.Exception_Occurrence Id_JNI_392 = Id_JNI_389;
         return Id_JNI_392;
      } finally {
         quiz.Ada2Java.Library.lock.unlock ();
      }
   } // createOccurrence

   native static private int [] createOccurrence_Id_JNI_372 (int [] Message);

   static {
      quiz.Ada2Java.Library.load ();
   }

} // Storage_Error
