/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          *
 * Original Ada unit: Standard                                               *
 * Generation timestamp: 201412211026                                        *
 *****************************************************************************/

package adarecord.Standard;

/**
 */
@SuppressWarnings("all")
public final class Storage_Error extends com.adacore.ajis.NativeException implements com.adacore.ajis.internal.ada.AdaException {

   adarecord.Ada.Exceptions.Exception_Occurrence Id_JNI_506;

   private Storage_Error (String message, int [] addr) {
      super (message);
      Id_JNI_506 = new adarecord.Ada.Exceptions.Exception_Occurrence (new com.adacore.ajis.internal.ada.AdaAccess (addr));
      Id_JNI_506.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
      Id_JNI_506.myOwner = com.adacore.ajis.IProxy.Owner.PROXY;
   }

   public Storage_Error (adarecord.Standard.AdaString message) {
      super (message.toString());
      Id_JNI_506 = createOccurrence (message);
   }

   public int [] getExceptionAddr () {
      return Id_JNI_506.getAccess ();
   }

   /**
    * @param Message is passed by value
    * @return is passed by reference (escapable)
    */
   static public adarecord.Ada.Exceptions.Exception_Occurrence createOccurrence (adarecord.Standard.AdaString Message) {
      adarecord.Ada2Java.Library.lock.lock ();
      try {
         adarecord.Standard.AdaString Id_JNI_509 = Message;
         if (Id_JNI_509 == null) {
            throw new com.adacore.ajis.NativeException ("null not allowed for Message");
         }
         int [] Id_JNI_516;
         adarecord.Standard.AdaString Id_JNI_517 = Id_JNI_509;
         Id_JNI_516 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_517).getAccess ();
         int [] Id_JNI_522 = createOccurrence_Id_JNI_507 (Id_JNI_516);
         adarecord.Ada.Exceptions.Exception_Occurrence Id_JNI_523;
         if (com.adacore.ajis.internal.ada.AdaAccess.isNull (Id_JNI_522)) {
            Id_JNI_523 = null;
         } else {
            Id_JNI_523 = new adarecord.Ada.Exceptions.Exception_Occurrence (new com.adacore.ajis.internal.ada.AdaAccess (Id_JNI_522));
         }
         adarecord.Ada.Exceptions.Exception_Occurrence Id_JNI_524 = Id_JNI_523;
         if (Id_JNI_524 != null) {
            Id_JNI_524.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
         }
         adarecord.Ada.Exceptions.Exception_Occurrence Id_JNI_527 = Id_JNI_524;
         return Id_JNI_527;
      } finally {
         adarecord.Ada2Java.Library.lock.unlock ();
      }
   } // createOccurrence

   native static private int [] createOccurrence_Id_JNI_507 (int [] Message);

   static {
      adarecord.Ada2Java.Library.load ();
   }

} // Storage_Error
