/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          *
 * Original Ada unit: Record_Types                                           *
 * Generation timestamp: 201412211026                                        *
 *****************************************************************************/

package adarecord.Record_Types;

/**
 * @origin record_types.ads:1:9
 */
@SuppressWarnings("all")
public final class Record_Types_Package {

   /**
    * @origin record_types.ads:16:13
    * @param Obj is passed by value
    * @return is passed by value
    */
   static public adarecord.Standard.AdaString As_String (adarecord.Record_Types.A_Nested_Record_Type Obj) {
      adarecord.Ada2Java.Library.lock.lock ();
      try {
         adarecord.Record_Types.A_Nested_Record_Type Id_JNI_242 = Obj;
         if (Id_JNI_242 == null) {
            throw new com.adacore.ajis.NativeException ("null not allowed for Obj");
         }
         int [] Id_JNI_244;
         adarecord.Record_Types.A_Nested_Record_Type Id_JNI_245 = Id_JNI_242;
         Id_JNI_244 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_245).getAccess ();
         int [] Id_JNI_249 = As_String_Id_JNI_240 (Id_JNI_244);
         adarecord.Standard.AdaString Id_JNI_250;
         Id_JNI_250 = new adarecord.Standard.AdaString (new com.adacore.ajis.internal.ada.AdaAccess (Id_JNI_249));
         Id_JNI_250.myOwner = com.adacore.ajis.IProxy.Owner.PROXY;
         adarecord.Standard.AdaString Id_JNI_251 = Id_JNI_250;
         if (Id_JNI_251 != null) {
            Id_JNI_251.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
         }
         adarecord.Standard.AdaString Id_JNI_254 = Id_JNI_251;
         return Id_JNI_254;
      } finally {
         adarecord.Ada2Java.Library.lock.unlock ();
      }
   } // As_String

   native static private int [] As_String_Id_JNI_240 (int [] Obj);

   static {
      adarecord.Ada2Java.Library.load ();
   }

} // Record_Types_Package
