/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          *
 * Original Ada unit: Standard                                               *
 * Generation timestamp: 201501031502                                        *
 *****************************************************************************/

package jprinter.Standard;

/**
 */
@SuppressWarnings("all")
public final class AdaString extends com.adacore.ajis.internal.ada.AdaProxy {

   /**
    * @param this is passed by reference (non escapable)
    * @param Right is passed by reference (non escapable)
    */
   final public boolean equals (java.lang.Object Right) {
      jprinter.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_86;
         java.lang.Object Id_JNI_87 = this;
         if (this.getClass () != Right.getClass ()) return false;
         if (Id_JNI_87 == null) {
            Id_JNI_86 = jprinter.Standard.AdaString.nullArrayAccess ();
         } else {
            Id_JNI_86 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_87).getAccess ();
         }
         int [] Id_JNI_95;
         java.lang.Object Id_JNI_96 = ((com.adacore.ajis.internal.ada.AdaProxy) Right);
         if (Id_JNI_96 == null) {
            Id_JNI_95 = jprinter.Standard.AdaString.nullArrayAccess ();
         } else {
            Id_JNI_95 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_96).getAccess ();
         }
         boolean Id_JNI_100 = equals_Id_JNI_77 (Id_JNI_86, Id_JNI_95);
         return Id_JNI_100;
      } finally {
         jprinter.Ada2Java.Library.lock.unlock ();
      }
   } // equals

   /**
    * @param this is passed by reference (non escapable)
    * @return is passed by reference (escapable)
    */
   public int [] internalClone () {
      jprinter.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_113;
         jprinter.Standard.AdaString Id_JNI_114 = this;
         if (Id_JNI_114 == null) {
            Id_JNI_113 = jprinter.Standard.AdaString.nullArrayAccess ();
         } else {
            Id_JNI_113 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_114).getAccess ();
         }
         int [] Id_JNI_122 = ((int []) internalClone_Id_JNI_104 (Id_JNI_113));
         return Id_JNI_122;
      } finally {
         jprinter.Ada2Java.Library.lock.unlock ();
      }
   } // internalClone

   /**
    * @return is passed by reference (escapable)
    */
   public AdaString (int First_1, int Last_1) {
      super (new com.adacore.ajis.internal.ada.AdaAccess (null));
      jprinter.Ada2Java.Library.lock.lock ();
      try {
         this.adaAccess = AdaString_Id_JNI_126 (First_1, Last_1);
         this.myOwner = com.adacore.ajis.IProxy.Owner.PROXY;
         this.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
      } finally {
         jprinter.Ada2Java.Library.lock.unlock ();
      }
   } // AdaString

   public AdaString (com.adacore.ajis.internal.ada.AdaAccess access) {
      this.adaAccess = access.fAcc;
   }

   /**
    * @param this is passed by reference (non escapable)
    */
   public void deallocateNativeObject () {
      jprinter.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_148;
         jprinter.Standard.AdaString Id_JNI_149 = this;
         if (Id_JNI_149 == null) {
            Id_JNI_148 = jprinter.Standard.AdaString.nullArrayAccess ();
         } else {
            Id_JNI_148 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_149).getAccess ();
         }
         deallocateNativeObject_Id_JNI_139 (Id_JNI_148);
      } finally {
         jprinter.Ada2Java.Library.lock.unlock ();
      }
   } // deallocateNativeObject

   /**
    * @param this is passed by reference (non escapable)
    */
   final public char Get_Element_At (int Index_1) {
      jprinter.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_160;
         jprinter.Standard.AdaString Id_JNI_161 = this;
         if (Id_JNI_161 == null) {
            Id_JNI_160 = jprinter.Standard.AdaString.nullArrayAccess ();
         } else {
            Id_JNI_160 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_161).getAccess ();
         }
         char Id_JNI_167 = Get_Element_At_Id_JNI_151 (Id_JNI_160, Index_1);
         return Id_JNI_167;
      } finally {
         jprinter.Ada2Java.Library.lock.unlock ();
      }
   } // Get_Element_At

   /**
    * @param this is passed by reference (non escapable)
    */
   final public void Set_Element_At (int Index_1, char Value) {
      jprinter.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_180;
         jprinter.Standard.AdaString Id_JNI_181 = this;
         if (Id_JNI_181 == null) {
            Id_JNI_180 = jprinter.Standard.AdaString.nullArrayAccess ();
         } else {
            Id_JNI_180 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_181).getAccess ();
         }
         Set_Element_At_Id_JNI_171 (Id_JNI_180, Index_1, Value);
      } finally {
         jprinter.Ada2Java.Library.lock.unlock ();
      }
   } // Set_Element_At

   /**
    * @param this is passed by value
    */
   final public int First () {
      jprinter.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_193;
         jprinter.Standard.AdaString Id_JNI_194 = this;
         Id_JNI_193 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_194).getAccess ();
         int Id_JNI_198 = First_Id_JNI_184 (Id_JNI_193);
         return Id_JNI_198;
      } finally {
         jprinter.Ada2Java.Library.lock.unlock ();
      }
   } // First

   /**
    * @param this is passed by value
    */
   final public int Last () {
      jprinter.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_211;
         jprinter.Standard.AdaString Id_JNI_212 = this;
         Id_JNI_211 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_212).getAccess ();
         int Id_JNI_216 = Last_Id_JNI_202 (Id_JNI_211);
         return Id_JNI_216;
      } finally {
         jprinter.Ada2Java.Library.lock.unlock ();
      }
   } // Last

   /**
    * @param this is passed by value
    */
   final public int Length () {
      jprinter.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_229;
         jprinter.Standard.AdaString Id_JNI_230 = this;
         Id_JNI_229 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_230).getAccess ();
         int Id_JNI_234 = Length_Id_JNI_220 (Id_JNI_229);
         return Id_JNI_234;
      } finally {
         jprinter.Ada2Java.Library.lock.unlock ();
      }
   } // Length

   /**
    * @return is passed by reference (escapable)
    */
   static public int [] createNullAccess () {
      jprinter.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_246 = ((int []) createNullAccess_Id_JNI_238 ());
         return Id_JNI_246;
      } finally {
         jprinter.Ada2Java.Library.lock.unlock ();
      }
   } // createNullAccess

   private static int [] nullArrayAccessVal;

   public static int [] nullArrayAccess () {
      if (nullArrayAccessVal == null) {
         nullArrayAccessVal = createNullAccess ();
      }
      return nullArrayAccessVal;
   }

   /**
    * @param this is passed by value
    * @return is passed by value
    */
   final public java.lang.String toString () {
      jprinter.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_259;
         jprinter.Standard.AdaString Id_JNI_260 = this;
         Id_JNI_259 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_260).getAccess ();
         java.lang.String Id_JNI_264 = toString_Id_JNI_250 (Id_JNI_259);
         return Id_JNI_264;
      } finally {
         jprinter.Ada2Java.Library.lock.unlock ();
      }
   } // toString

   /**
    * @param Str is passed by value
    * @return is passed by reference (escapable)
    */
   public AdaString (java.lang.String Str) {
      jprinter.Ada2Java.Library.lock.lock ();
      try {
         java.lang.String Id_JNI_269 = Str;
         if (Id_JNI_269 == null) {
            throw new com.adacore.ajis.NativeException ("null not allowed for Str");
         }
         this.adaAccess = AdaString_Id_JNI_267 (Id_JNI_269);
         this.myOwner = com.adacore.ajis.IProxy.Owner.PROXY;
         this.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
      } finally {
         jprinter.Ada2Java.Library.lock.unlock ();
      }
   } // AdaString

   native private boolean equals_Id_JNI_77 (int [] Left, int [] Right);

   native private int [] internalClone_Id_JNI_104 (int [] This);

   native private int [] AdaString_Id_JNI_126 (int First_1, int Last_1);

   native private void deallocateNativeObject_Id_JNI_139 (int [] Obj);

   native private char Get_Element_At_Id_JNI_151 (int [] This, int Index_1);

   native private void Set_Element_At_Id_JNI_171 (int [] This, int Index_1, char Value);

   native private int First_Id_JNI_184 (int [] This);

   native private int Last_Id_JNI_202 (int [] This);

   native private int Length_Id_JNI_220 (int [] This);

   native static private int [] createNullAccess_Id_JNI_238 ();

   native private java.lang.String toString_Id_JNI_250 (int [] This);

   native private int [] AdaString_Id_JNI_267 (java.lang.String Str);

   static {
      jprinter.Ada2Java.Library.load ();
   }

} // AdaString
