/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          *
 * Original Ada unit: Standard                                               *
 * Generation timestamp: 201501031502                                        *
 *****************************************************************************/

package jprinter.Standard;

/**
 */
@SuppressWarnings("all")
public final class Constraint_Error extends com.adacore.ajis.NativeException implements com.adacore.ajis.internal.ada.AdaException {

   jprinter.Ada.Exceptions.Exception_Occurrence Id_JNI_277;

   private Constraint_Error (String message, int [] addr) {
      super (message);
      Id_JNI_277 = new jprinter.Ada.Exceptions.Exception_Occurrence (new com.adacore.ajis.internal.ada.AdaAccess (addr));
      Id_JNI_277.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
      Id_JNI_277.myOwner = com.adacore.ajis.IProxy.Owner.PROXY;
   }

   public Constraint_Error (jprinter.Standard.AdaString message) {
      super (message.toString());
      Id_JNI_277 = createOccurrence (message);
   }

   public int [] getExceptionAddr () {
      return Id_JNI_277.getAccess ();
   }

   /**
    * @param Message is passed by value
    * @return is passed by reference (escapable)
    */
   static public jprinter.Ada.Exceptions.Exception_Occurrence createOccurrence (jprinter.Standard.AdaString Message) {
      jprinter.Ada2Java.Library.lock.lock ();
      try {
         jprinter.Standard.AdaString Id_JNI_280 = Message;
         if (Id_JNI_280 == null) {
            throw new com.adacore.ajis.NativeException ("null not allowed for Message");
         }
         int [] Id_JNI_287;
         jprinter.Standard.AdaString Id_JNI_288 = Id_JNI_280;
         Id_JNI_287 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_288).getAccess ();
         int [] Id_JNI_293 = createOccurrence_Id_JNI_278 (Id_JNI_287);
         jprinter.Ada.Exceptions.Exception_Occurrence Id_JNI_294;
         if (com.adacore.ajis.internal.ada.AdaAccess.isNull (Id_JNI_293)) {
            Id_JNI_294 = null;
         } else {
            Id_JNI_294 = new jprinter.Ada.Exceptions.Exception_Occurrence (new com.adacore.ajis.internal.ada.AdaAccess (Id_JNI_293));
         }
         jprinter.Ada.Exceptions.Exception_Occurrence Id_JNI_295 = Id_JNI_294;
         if (Id_JNI_295 != null) {
            Id_JNI_295.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
         }
         jprinter.Ada.Exceptions.Exception_Occurrence Id_JNI_298 = Id_JNI_295;
         return Id_JNI_298;
      } finally {
         jprinter.Ada2Java.Library.lock.unlock ();
      }
   } // createOccurrence

   native static private int [] createOccurrence_Id_JNI_278 (int [] Message);

   static {
      jprinter.Ada2Java.Library.load ();
   }

} // Constraint_Error
