/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          *
 * Original Ada unit: Standard                                               *
 * Generation timestamp: 201501031502                                        *
 *****************************************************************************/

package jprinter.Standard;

/**
 */
@SuppressWarnings("all")
public final class Program_Error extends com.adacore.ajis.NativeException implements com.adacore.ajis.internal.ada.AdaException {

   jprinter.Ada.Exceptions.Exception_Occurrence Id_JNI_301;

   private Program_Error (String message, int [] addr) {
      super (message);
      Id_JNI_301 = new jprinter.Ada.Exceptions.Exception_Occurrence (new com.adacore.ajis.internal.ada.AdaAccess (addr));
      Id_JNI_301.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
      Id_JNI_301.myOwner = com.adacore.ajis.IProxy.Owner.PROXY;
   }

   public Program_Error (jprinter.Standard.AdaString message) {
      super (message.toString());
      Id_JNI_301 = createOccurrence (message);
   }

   public int [] getExceptionAddr () {
      return Id_JNI_301.getAccess ();
   }

   /**
    * @param Message is passed by value
    * @return is passed by reference (escapable)
    */
   static public jprinter.Ada.Exceptions.Exception_Occurrence createOccurrence (jprinter.Standard.AdaString Message) {
      jprinter.Ada2Java.Library.lock.lock ();
      try {
         jprinter.Standard.AdaString Id_JNI_304 = Message;
         if (Id_JNI_304 == null) {
            throw new com.adacore.ajis.NativeException ("null not allowed for Message");
         }
         int [] Id_JNI_311;
         jprinter.Standard.AdaString Id_JNI_312 = Id_JNI_304;
         Id_JNI_311 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_312).getAccess ();
         int [] Id_JNI_317 = createOccurrence_Id_JNI_302 (Id_JNI_311);
         jprinter.Ada.Exceptions.Exception_Occurrence Id_JNI_318;
         if (com.adacore.ajis.internal.ada.AdaAccess.isNull (Id_JNI_317)) {
            Id_JNI_318 = null;
         } else {
            Id_JNI_318 = new jprinter.Ada.Exceptions.Exception_Occurrence (new com.adacore.ajis.internal.ada.AdaAccess (Id_JNI_317));
         }
         jprinter.Ada.Exceptions.Exception_Occurrence Id_JNI_319 = Id_JNI_318;
         if (Id_JNI_319 != null) {
            Id_JNI_319.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
         }
         jprinter.Ada.Exceptions.Exception_Occurrence Id_JNI_322 = Id_JNI_319;
         return Id_JNI_322;
      } finally {
         jprinter.Ada2Java.Library.lock.unlock ();
      }
   } // createOccurrence

   native static private int [] createOccurrence_Id_JNI_302 (int [] Message);

   static {
      jprinter.Ada2Java.Library.load ();
   }

} // Program_Error
