/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          *
 * Original Ada unit: JPrinter                                               *
 * Generation timestamp: 201501031502                                        *
 *****************************************************************************/

package jprinter.JPrinter;
import jprinter.JPrinter.Print_CB;

/**
 * @origin jprinter.ads:1:9
 */
@SuppressWarnings("all")
public final class Id_JNI_42 extends Print_CB {

   int [] adaAccess;

   public Id_JNI_42 (com.adacore.ajis.internal.ada.AdaAccess access) {
      this.adaAccess = access.fAcc;
   }

   public boolean isEscapable () {
      return true;
   }

   /**
    * @origin jprinter.ads:3:9
    * @param this is passed by reference (non escapable)
    * @param Str is passed by value
    */
   final public void Print_CB_Body (jprinter.Standard.AdaString Str) {
      jprinter.Ada2Java.Library.lock.lock ();
      try {
         jprinter.Standard.AdaString Id_JNI_68 = Str;
         if (Id_JNI_68 == null) {
            throw new com.adacore.ajis.NativeException ("null not allowed for Str");
         }
         int [] Id_JNI_75;
         jprinter.Standard.AdaString Id_JNI_76 = Id_JNI_68;
         Id_JNI_75 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_76).getAccess ();
         Print_CB_Body_Id_JNI_63 (this.adaAccess, Id_JNI_75);
      } finally {
         jprinter.Ada2Java.Library.lock.unlock ();
      }
   } // Print_CB_Body

   native private void Print_CB_Body_Id_JNI_63 (int [] This, int [] Str);

   static {
      jprinter.Ada2Java.Library.load ();
   }

} // Id_JNI_42
