/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          *
 * Original Ada unit: JPrinter                                               *
 * Generation timestamp: 201501031502                                        *
 *****************************************************************************/

package jprinter.JPrinter;
import jprinter.JPrinter.Print_CB;

/**
 * @origin jprinter.ads:1:9
 */
@SuppressWarnings("all")
public final class JPrinter_Package {

   /**
    * @origin jprinter.ads:5:14
    * @param Meth is passed by reference (non escapable)
    * @param Str is passed by value
    */
   static public void Call_Back (jprinter.JPrinter.Print_CB Meth, jprinter.Standard.AdaString Str) {
      jprinter.Ada2Java.Library.lock.lock ();
      try {
         jprinter.Standard.AdaString Id_JNI_46 = Str;
         if (Id_JNI_46 == null) {
            throw new com.adacore.ajis.NativeException ("null not allowed for Str");
         }
         int [] Id_JNI_54;
         jprinter.Standard.AdaString Id_JNI_55 = Id_JNI_46;
         Id_JNI_54 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_55).getAccess ();
         Call_Back_Id_JNI_39 (Meth, Id_JNI_54);
      } finally {
         jprinter.Ada2Java.Library.lock.unlock ();
      }
   } // Call_Back

   native static private void Call_Back_Id_JNI_39 (jprinter.JPrinter.Print_CB Meth, int [] Str);

   static {
      jprinter.Ada2Java.Library.load ();
   }

} // JPrinter_Package
