/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          *
 * Original Ada unit: JPrinter                                               *
 * Generation timestamp: 201501031502                                        *
 *****************************************************************************/

package jprinter.JPrinter;
import jprinter.JPrinter.Id_JNI_42;

/**
 * @origin jprinter.ads:3:9
 */
@SuppressWarnings("all")
public abstract class Print_CB implements com.adacore.ajis.IEscapable {

   /**
    * @origin jprinter.ads:3:9
    * @param Str is passed by value
    */
   abstract public void Print_CB_Body (jprinter.Standard.AdaString Str);

   public boolean isEscapable () {
      return false;
   }

   private void Print_CB_Body_Id_JNI_57_Callback (int [] Str) {
      int [] Id_JNI_59 = Str;
      jprinter.Standard.AdaString Id_JNI_60;
      Id_JNI_60 = new jprinter.Standard.AdaString (new com.adacore.ajis.internal.ada.AdaAccess (Id_JNI_59));
      jprinter.Standard.AdaString Id_JNI_61 = Id_JNI_60;
      Id_JNI_61.myAllocator = com.adacore.ajis.IProxy.Allocator.STATIC;
      Print_CB_Body (Id_JNI_61);
   } // Print_CB_Body_Id_JNI_57_Callback

   static {
      jprinter.Ada2Java.Library.load ();
   }

} // Print_CB
