-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          --
-- Original Ada unit: Record_Types                                           --
-- Generation timestamp: 201412211026                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Interfaces.Java.JNI;
with AJIS;
with AJIS.Internal;
with AJIS.Java;
with AJIS.Internal.Java;
with Ada.Characters.Conversions;
with Ada.Finalization;
with Record_Types; use Record_Types;
with JNI_Binding.Record_Types_JNI;
with JNI_Binding.Standard_JNI;
with Record_Types;

package JNI_Binding.Record_Types_JNI.Record_Types_Package_JNI is 

   procedure JNI_For_Body_Elaboration;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access);

   function Id_JNI_241 (Obj : Record_Types.A_Nested_Record_Type) return Standard.String;

   function As_String_Id_JNI_240 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_3 : Interfaces.Java.JNI.J_Class; Obj : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int_J_Array;
   pragma Export (C, As_String_Id_JNI_240, "Java_adarecord_Record_1Types_Record_1Types_1Package_As_1String_1Id_1JNI_1240___3I");

end JNI_Binding.Record_Types_JNI.Record_Types_Package_JNI;
