-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          --
-- Original Ada unit: Standard                                               --
-- Generation timestamp: 201412211026                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Ada.Unchecked_Deallocation;
with System.Address_To_Access_Conversions;
with Ada.Unchecked_Conversion;
with Ada.Tags;
with Ada.Exceptions;
with Interfaces.C;
with Interfaces.C.Strings;

package body JNI_Binding.Standard_JNI.AdaString_JNI is 

   procedure JNI_For_Body_Elaboration is begin null; end;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access) is
   begin

      null;
      AJIS.Internal.Java.Initialize (Id_JNI_246, Id_JNI_1);
   end Initialize_Unit_JNI;

   function Id_JNI_259 (Left : access constant Standard.String; Right : access constant Standard.String) return Standard.Boolean is
      Id_JNI_279 : Standard.Boolean := Standard."=" (Left.all, Right.all);
   begin
      return Id_JNI_279;
   end Id_JNI_259;

   function equals_Id_JNI_258 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Left : Interfaces.Java.JNI.J_Int_J_Array; Right : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Boolean is
   begin
      declare
         Id_JNI_261 : constant JNI_Binding.Standard_JNI.Id_JNI_248.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_248.To_Object_Pointer (Id_JNI_1, Left);
         Id_JNI_266 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_248.Get_Address (Id_JNI_261);
         subtype Id_JNI_262 is Standard.String (Id_JNI_261.Bound_1_Low .. Id_JNI_261.Bound_1_High);
         type Id_JNI_263 is access all Id_JNI_262;
         package Id_JNI_264 is new System.Address_To_Access_Conversions (Id_JNI_262);
         Id_JNI_265 : JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_261.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_265 := Id_JNI_264.To_Pointer (Id_JNI_266).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_261.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_265 := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer_Cst (Id_JNI_261.General_Pointer);
         else
            Id_JNI_265 := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer_Cst (Id_JNI_261.Constant_Pointer);
         end if;
         declare
            Id_JNI_270 : constant JNI_Binding.Standard_JNI.Id_JNI_248.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_248.To_Object_Pointer (Id_JNI_1, Right);
            Id_JNI_275 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_248.Get_Address (Id_JNI_270);
            subtype Id_JNI_271 is Standard.String (Id_JNI_270.Bound_1_Low .. Id_JNI_270.Bound_1_High);
            type Id_JNI_272 is access all Id_JNI_271;
            package Id_JNI_273 is new System.Address_To_Access_Conversions (Id_JNI_271);
            Id_JNI_274 : JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer_Cst;
         begin
            if AJIS.Internal.Java."=" (Id_JNI_270.Kind, AJIS.Internal.Java.Static) then
               Id_JNI_274 := Id_JNI_273.To_Pointer (Id_JNI_275).all'Unrestricted_Access;
            elsif AJIS.Internal.Java."=" (Id_JNI_270.Kind, AJIS.Internal.Java.General_Access) then
               Id_JNI_274 := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer_Cst (Id_JNI_270.General_Pointer);
            else
               Id_JNI_274 := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer_Cst (Id_JNI_270.Constant_Pointer);
            end if;
            declare
               Id_JNI_280 : Interfaces.Java.JNI.J_Boolean := Interfaces.Java.JNI.J_Boolean (Id_JNI_259 (Id_JNI_265, Id_JNI_274));
            begin
               return Id_JNI_280;
            end;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Boolean (False);
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Boolean (False);
         end;
   end equals_Id_JNI_258;

   function Id_JNI_286 (This : access Standard.String) return access Standard.String is
      Id_JNI_296 : JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer := new Standard.String'(This.all);
      Id_JNI_301 : JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer (Id_JNI_296);
   begin
      return Id_JNI_301;
   end Id_JNI_286;

   function internalClone_Id_JNI_285 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_288 : constant JNI_Binding.Standard_JNI.Id_JNI_248.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_248.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_293 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_248.Get_Address (Id_JNI_288);
         subtype Id_JNI_289 is Standard.String (Id_JNI_288.Bound_1_Low .. Id_JNI_288.Bound_1_High);
         type Id_JNI_290 is access all Id_JNI_289;
         package Id_JNI_291 is new System.Address_To_Access_Conversions (Id_JNI_289);
         Id_JNI_292 : JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_288.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_292 := Id_JNI_291.To_Pointer (Id_JNI_293).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_288.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_292 := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer (Id_JNI_288.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
            Id_JNI_298_Proxy : Interfaces.Java.JNI.J_Object;
            Id_JNI_299_Ptr : JNI_Binding.Standard_JNI.Id_JNI_248.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_248.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_248.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer (Id_JNI_286 (Id_JNI_292))));
         begin
            declare
               Id_JNI_302 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_248.To_J_Int_J_Array (Id_JNI_1, Id_JNI_299_Ptr);
            begin
               return Id_JNI_302;
            end;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end internalClone_Id_JNI_285;

   function Id_JNI_308 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; First_1 : Standard.Integer'Base; Last_1 : Standard.Integer'Base) return access Standard.String is
      Id_JNI_315 : JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer (JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer'( new Standard.String (First_1 .. Last_1)));
   begin
      return Id_JNI_315;
   end Id_JNI_308;

   function AdaString_Id_JNI_307 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; First_1 : Interfaces.Java.JNI.J_Int; Last_1 : Interfaces.Java.JNI.J_Int) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_312_Proxy : Interfaces.Java.JNI.J_Object;
         Id_JNI_313_Ptr : JNI_Binding.Standard_JNI.Id_JNI_248.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_248.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_248.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer (Id_JNI_308(Id_JNI_1, Id_JNI_2, Standard.Integer'Base (First_1), Standard.Integer'Base (Last_1)))));
      begin
         declare
            Id_JNI_316 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_248.To_J_Int_J_Array (Id_JNI_1, Id_JNI_313_Ptr);
         begin
            return Id_JNI_316;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end AdaString_Id_JNI_307;

   procedure Id_JNI_321 (Obj : access Standard.String) is
      Id_JNI_331 : JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer (Obj);
   begin
      JNI_Binding.Standard_JNI.Id_JNI_248.Free (Id_JNI_331);
   end Id_JNI_321;

   procedure deallocateNativeObject_Id_JNI_320 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Obj : Interfaces.Java.JNI.J_Int_J_Array) is
   begin
      declare
         Id_JNI_323 : constant JNI_Binding.Standard_JNI.Id_JNI_248.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_248.To_Object_Pointer (Id_JNI_1, Obj);
         Id_JNI_328 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_248.Get_Address (Id_JNI_323);
         subtype Id_JNI_324 is Standard.String (Id_JNI_323.Bound_1_Low .. Id_JNI_323.Bound_1_High);
         type Id_JNI_325 is access all Id_JNI_324;
         package Id_JNI_326 is new System.Address_To_Access_Conversions (Id_JNI_324);
         Id_JNI_327 : JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_323.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_327 := Id_JNI_326.To_Pointer (Id_JNI_328).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_323.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_327 := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer (Id_JNI_323.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
         begin
            Id_JNI_321 (Id_JNI_327);
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
         end;
   end deallocateNativeObject_Id_JNI_320;

   function Id_JNI_333 (This : access Standard.String; Index_1 : Standard.Integer'Base) return Standard.Character is
      Id_JNI_346 : Standard.Character := This (Index_1);
   begin
      return Id_JNI_346;
   end Id_JNI_333;

   function Get_Element_At_Id_JNI_332 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Index_1 : Interfaces.Java.JNI.J_Int) return Interfaces.Java.JNI.J_Char is
   begin
      declare
         Id_JNI_335 : constant JNI_Binding.Standard_JNI.Id_JNI_248.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_248.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_340 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_248.Get_Address (Id_JNI_335);
         subtype Id_JNI_336 is Standard.String (Id_JNI_335.Bound_1_Low .. Id_JNI_335.Bound_1_High);
         type Id_JNI_337 is access all Id_JNI_336;
         package Id_JNI_338 is new System.Address_To_Access_Conversions (Id_JNI_336);
         Id_JNI_339 : JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_335.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_339 := Id_JNI_338.To_Pointer (Id_JNI_340).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_335.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_339 := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer (Id_JNI_335.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
            Id_JNI_347 : Interfaces.Java.JNI.J_Char := Interfaces.Java.JNI.J_Char (Ada.Characters.Conversions.To_Wide_Character (Id_JNI_333 (Id_JNI_339, Standard.Integer'Base (Index_1))));
         begin
            return Id_JNI_347;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Char (Ada.Characters.Conversions.To_Wide_Character (ASCII.NUL));
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Char (Ada.Characters.Conversions.To_Wide_Character (ASCII.NUL));
         end;
   end Get_Element_At_Id_JNI_332;

   procedure Id_JNI_353 (This : access Standard.String; Index_1 : Standard.Integer'Base; Value : Standard.Character) is
   begin
      This (Index_1) := Value;
   end Id_JNI_353;

   procedure Set_Element_At_Id_JNI_352 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Index_1 : Interfaces.Java.JNI.J_Int; Value : Interfaces.Java.JNI.J_Char) is
   begin
      declare
         Id_JNI_355 : constant JNI_Binding.Standard_JNI.Id_JNI_248.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_248.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_360 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_248.Get_Address (Id_JNI_355);
         subtype Id_JNI_356 is Standard.String (Id_JNI_355.Bound_1_Low .. Id_JNI_355.Bound_1_High);
         type Id_JNI_357 is access all Id_JNI_356;
         package Id_JNI_358 is new System.Address_To_Access_Conversions (Id_JNI_356);
         Id_JNI_359 : JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_355.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_359 := Id_JNI_358.To_Pointer (Id_JNI_360).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_355.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_359 := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer (Id_JNI_355.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
         begin
            Id_JNI_353 (Id_JNI_359, Standard.Integer'Base (Index_1), Standard.Character (Ada.Characters.Conversions.To_Character (Wide_Character (Value))));
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
         end;
   end Set_Element_At_Id_JNI_352;

   function Id_JNI_366 (This : Standard.String) return Standard.Integer'Base is
      Id_JNI_377 : Standard.Integer'Base := This'First;
   begin
      return Id_JNI_377;
   end Id_JNI_366;

   function First_Id_JNI_365 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int is
   begin
      declare
         Id_JNI_368 : JNI_Binding.Standard_JNI.Id_JNI_248.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_248.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_373 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_248.Get_Address (Id_JNI_368);
         subtype Id_JNI_369 is Standard.String (Id_JNI_368.Bound_1_Low .. Id_JNI_368.Bound_1_High);
         type Id_JNI_370 is access all Id_JNI_369;
         package Id_JNI_371 is new System.Address_To_Access_Conversions (Id_JNI_369);
         Id_JNI_372 : JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_368.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_372 := Id_JNI_371.To_Pointer (Id_JNI_373).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_368.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_372 := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer_Cst (Id_JNI_368.General_Pointer);
         else
            Id_JNI_372 := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer_Cst (Id_JNI_368.Constant_Pointer);
         end if;
         declare
            Id_JNI_378 : Interfaces.Java.JNI.J_Int := Interfaces.Java.JNI.J_Int (Id_JNI_366 (Standard.String (Id_JNI_372.all)));
         begin
            return Id_JNI_378;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return 0;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return 0;
         end;
   end First_Id_JNI_365;

   function Id_JNI_384 (This : Standard.String) return Standard.Integer'Base is
      Id_JNI_395 : Standard.Integer'Base := This'Last;
   begin
      return Id_JNI_395;
   end Id_JNI_384;

   function Last_Id_JNI_383 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int is
   begin
      declare
         Id_JNI_386 : JNI_Binding.Standard_JNI.Id_JNI_248.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_248.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_391 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_248.Get_Address (Id_JNI_386);
         subtype Id_JNI_387 is Standard.String (Id_JNI_386.Bound_1_Low .. Id_JNI_386.Bound_1_High);
         type Id_JNI_388 is access all Id_JNI_387;
         package Id_JNI_389 is new System.Address_To_Access_Conversions (Id_JNI_387);
         Id_JNI_390 : JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_386.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_390 := Id_JNI_389.To_Pointer (Id_JNI_391).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_386.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_390 := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer_Cst (Id_JNI_386.General_Pointer);
         else
            Id_JNI_390 := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer_Cst (Id_JNI_386.Constant_Pointer);
         end if;
         declare
            Id_JNI_396 : Interfaces.Java.JNI.J_Int := Interfaces.Java.JNI.J_Int (Id_JNI_384 (Standard.String (Id_JNI_390.all)));
         begin
            return Id_JNI_396;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return 0;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return 0;
         end;
   end Last_Id_JNI_383;

   function Id_JNI_402 (This : Standard.String) return Standard.Integer is
      Id_JNI_413 : Standard.Integer := This'Length;
   begin
      return Id_JNI_413;
   end Id_JNI_402;

   function Length_Id_JNI_401 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int is
   begin
      declare
         Id_JNI_404 : JNI_Binding.Standard_JNI.Id_JNI_248.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_248.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_409 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_248.Get_Address (Id_JNI_404);
         subtype Id_JNI_405 is Standard.String (Id_JNI_404.Bound_1_Low .. Id_JNI_404.Bound_1_High);
         type Id_JNI_406 is access all Id_JNI_405;
         package Id_JNI_407 is new System.Address_To_Access_Conversions (Id_JNI_405);
         Id_JNI_408 : JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_404.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_408 := Id_JNI_407.To_Pointer (Id_JNI_409).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_404.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_408 := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer_Cst (Id_JNI_404.General_Pointer);
         else
            Id_JNI_408 := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer_Cst (Id_JNI_404.Constant_Pointer);
         end if;
         declare
            Id_JNI_414 : Interfaces.Java.JNI.J_Int := Interfaces.Java.JNI.J_Int (Id_JNI_402 (Standard.String (Id_JNI_408.all)));
         begin
            return Id_JNI_414;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return 0;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return 0;
         end;
   end Length_Id_JNI_401;

   function Id_JNI_420 return access Standard.String is
      Id_JNI_425 : JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer (JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer'(null));
   begin
      return Id_JNI_425;
   end Id_JNI_420;

   function createNullAccess_Id_JNI_419 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_3 : Interfaces.Java.JNI.J_Class) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_422_Proxy : Interfaces.Java.JNI.J_Object;
         Id_JNI_423_Ptr : JNI_Binding.Standard_JNI.Id_JNI_248.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_248.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_248.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer (Id_JNI_420)));
      begin
         declare
            Id_JNI_426 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_248.To_J_Int_J_Array (Id_JNI_1, Id_JNI_423_Ptr);
         begin
            return Id_JNI_426;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end createNullAccess_Id_JNI_419;

   function Id_JNI_432 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; This : Standard.String) return Interfaces.Java.JNI.J_String is
      Id_JNI_442 : Interfaces.C.Strings.chars_ptr;
      Id_JNI_443 : Interfaces.Java.JNI.J_String;
   begin
      Id_JNI_442 := Interfaces.C.Strings.New_String (String (This));
      Id_JNI_443 := Interfaces.Java.JNI.New_String_UTF (Id_JNI_1, Id_JNI_442);
      Interfaces.C.Strings.Free (Id_JNI_442);
      return Id_JNI_443;
   end Id_JNI_432;

   function toString_Id_JNI_431 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Object is
   begin
      declare
         Id_JNI_434 : JNI_Binding.Standard_JNI.Id_JNI_248.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_248.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_439 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_248.Get_Address (Id_JNI_434);
         subtype Id_JNI_435 is Standard.String (Id_JNI_434.Bound_1_Low .. Id_JNI_434.Bound_1_High);
         type Id_JNI_436 is access all Id_JNI_435;
         package Id_JNI_437 is new System.Address_To_Access_Conversions (Id_JNI_435);
         Id_JNI_438 : JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_434.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_438 := Id_JNI_437.To_Pointer (Id_JNI_439).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_434.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_438 := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer_Cst (Id_JNI_434.General_Pointer);
         else
            Id_JNI_438 := JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer_Cst (Id_JNI_434.Constant_Pointer);
         end if;
         declare
            Id_JNI_444 : Interfaces.Java.JNI.J_Object := Id_JNI_432 (Id_JNI_1, Standard.String (Id_JNI_438.all));
         begin
            return Id_JNI_444;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Object;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Object;
         end;
   end toString_Id_JNI_431;

   function Id_JNI_449 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Str : Interfaces.Java.JNI.J_String) return JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer is
      Is_Copy : aliased Interfaces.Java.JNI.J_Boolean;
      C_Str : constant Interfaces.C.Strings.chars_ptr := Interfaces.Java.JNI.Get_String_UTF_Chars (Id_JNI_1, Str, Is_Copy'Unchecked_Access);
      Ada_Str : constant AJIS.Internal.Java.Unchecked_String_Access := AJIS.Internal.Java.To_Unchecked_String (AJIS.Internal.Java.Convert (C_Str));
      pragma Suppress (Access_Check, Ada_Str);
      Result : JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer := new Standard.String'(Standard.String (Ada_Str (1 .. Integer (Interfaces.C.Strings.Strlen (C_Str)))));
   begin
      Interfaces.Java.JNI.Release_String_UTF_Chars (Id_JNI_1, Str, C_Str);
      return Result;
   end Id_JNI_449;

   function AdaString_Id_JNI_448 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Str : Interfaces.Java.JNI.J_Object) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_452_Proxy : Interfaces.Java.JNI.J_Object;
         Id_JNI_453_Ptr : JNI_Binding.Standard_JNI.Id_JNI_248.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_248.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_248.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer (Id_JNI_449(Id_JNI_1, Id_JNI_2, Str))));
      begin
         declare
            Id_JNI_455 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_248.To_J_Int_J_Array (Id_JNI_1, Id_JNI_453_Ptr);
         begin
            return Id_JNI_455;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end AdaString_Id_JNI_448;

begin
   null;
end JNI_Binding.Standard_JNI.AdaString_JNI;
