-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          --
-- Original Ada unit: Standard                                               --
-- Generation timestamp: 201412211026                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Interfaces.Java.JNI;
with AJIS;
with AJIS.Internal;
with AJIS.Java;
with AJIS.Internal.Java;
with Ada.Characters.Conversions;
with Ada.Finalization;
with Ada.Unchecked_Deallocation;
with System;

package JNI_Binding.Standard_JNI is 

   procedure JNI_For_Body_Elaboration;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access);

   package Id_JNI_248 is

      type Array_Pointer is access all Standard.String;

      type Array_Pointer_Cst is access constant Standard.String;

      type Object_Pointer
        (Kind : AJIS.Internal.Java.Array_Pointer_Kind := AJIS.Internal.Java.General_Access)
      is
         record
            
   Bound_1_Low, Bound_1_High : Standard.Integer'Base;

            case Kind is
               when AJIS.Internal.Java.Static =>
                  Addr : System.Address;

               when AJIS.Internal.Java.General_Access =>
                  General_Pointer : Array_Pointer;

               when AJIS.Internal.Java.Constant_Access =>
                  Constant_Pointer : Array_Pointer_Cst;

            end case;
         end record;

      Null_Pointer : constant Object_Pointer :=
        (AJIS.Internal.Java.General_Access, Standard.Positive'First, Standard.Positive'First,  null);

      function Create_General_Encapsulation
        (V : Array_Pointer) return Object_Pointer;
        
      function Create_Constant_Encapsulation
        (V : Array_Pointer_Cst) return Object_Pointer;

      function Get_Address (V : Object_Pointer) return System.Address;

      function To_J_Int_J_Array
        (Env : Interfaces.Java.JNI.JNI_Env_Access;
         Obj : Object_Pointer)
         return Interfaces.Java.JNI.J_Int_J_Array;

      function To_Object_Pointer
        (Env : Interfaces.Java.JNI.JNI_Env_Access;
         Obj : Interfaces.Java.JNI.J_Int_J_Array)
         return Object_Pointer;

      procedure Free is new Ada.Unchecked_Deallocation
        (Standard.String, Array_Pointer);

   end Id_JNI_248;


end JNI_Binding.Standard_JNI;
