-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          --
-- Original Ada unit: Standard                                               --
-- Generation timestamp: 201412211026                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Interfaces.Java.JNI;
with AJIS;
with AJIS.Internal;
with AJIS.Java;
with AJIS.Internal.Java;
with Ada.Characters.Conversions;
with Ada.Finalization;

package JNI_Binding.Standard_JNI.AdaString_JNI is 

   procedure JNI_For_Body_Elaboration;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access);

   function Id_JNI_259 (Left : access constant Standard.String; Right : access constant Standard.String) return Standard.Boolean;

   function equals_Id_JNI_258 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Left : Interfaces.Java.JNI.J_Int_J_Array; Right : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Boolean;
   pragma Export (C, equals_Id_JNI_258, "Java_adarecord_Standard_AdaString_equals_1Id_1JNI_1258___3I_3I");

   function Id_JNI_286 (This : access Standard.String) return access Standard.String;

   function internalClone_Id_JNI_285 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int_J_Array;
   pragma Export (C, internalClone_Id_JNI_285, "Java_adarecord_Standard_AdaString_internalClone_1Id_1JNI_1285___3I");

   function Id_JNI_308 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; First_1 : Standard.Integer'Base; Last_1 : Standard.Integer'Base) return access Standard.String;

   function AdaString_Id_JNI_307 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; First_1 : Interfaces.Java.JNI.J_Int; Last_1 : Interfaces.Java.JNI.J_Int) return Interfaces.Java.JNI.J_Int_J_Array;
   pragma Export (C, AdaString_Id_JNI_307, "Java_adarecord_Standard_AdaString_AdaString_1Id_1JNI_1307__II");

   procedure Id_JNI_321 (Obj : access Standard.String);

   procedure deallocateNativeObject_Id_JNI_320 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Obj : Interfaces.Java.JNI.J_Int_J_Array);
   pragma Export (C, deallocateNativeObject_Id_JNI_320, "Java_adarecord_Standard_AdaString_deallocateNativeObject_1Id_1JNI_1320___3I");

   function Id_JNI_333 (This : access Standard.String; Index_1 : Standard.Integer'Base) return Standard.Character;

   function Get_Element_At_Id_JNI_332 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Index_1 : Interfaces.Java.JNI.J_Int) return Interfaces.Java.JNI.J_Char;
   pragma Export (C, Get_Element_At_Id_JNI_332, "Java_adarecord_Standard_AdaString_Get_1Element_1At_1Id_1JNI_1332___3II");

   procedure Id_JNI_353 (This : access Standard.String; Index_1 : Standard.Integer'Base; Value : Standard.Character);

   procedure Set_Element_At_Id_JNI_352 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Index_1 : Interfaces.Java.JNI.J_Int; Value : Interfaces.Java.JNI.J_Char);
   pragma Export (C, Set_Element_At_Id_JNI_352, "Java_adarecord_Standard_AdaString_Set_1Element_1At_1Id_1JNI_1352___3IIC");

   function Id_JNI_366 (This : Standard.String) return Standard.Integer'Base;

   function First_Id_JNI_365 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int;
   pragma Export (C, First_Id_JNI_365, "Java_adarecord_Standard_AdaString_First_1Id_1JNI_1365___3I");

   function Id_JNI_384 (This : Standard.String) return Standard.Integer'Base;

   function Last_Id_JNI_383 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int;
   pragma Export (C, Last_Id_JNI_383, "Java_adarecord_Standard_AdaString_Last_1Id_1JNI_1383___3I");

   function Id_JNI_402 (This : Standard.String) return Standard.Integer;

   function Length_Id_JNI_401 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int;
   pragma Export (C, Length_Id_JNI_401, "Java_adarecord_Standard_AdaString_Length_1Id_1JNI_1401___3I");

   function Id_JNI_420 return access Standard.String;

   function createNullAccess_Id_JNI_419 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_3 : Interfaces.Java.JNI.J_Class) return Interfaces.Java.JNI.J_Int_J_Array;
   pragma Export (C, createNullAccess_Id_JNI_419, "Java_adarecord_Standard_AdaString_createNullAccess_1Id_1JNI_1419__");

   function Id_JNI_432 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; This : Standard.String) return Interfaces.Java.JNI.J_String;

   function toString_Id_JNI_431 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Object;
   pragma Export (C, toString_Id_JNI_431, "Java_adarecord_Standard_AdaString_toString_1Id_1JNI_1431___3I");

   function Id_JNI_449 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Str : Interfaces.Java.JNI.J_String) return JNI_Binding.Standard_JNI.Id_JNI_248.Array_Pointer;

   function AdaString_Id_JNI_448 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Str : Interfaces.Java.JNI.J_Object) return Interfaces.Java.JNI.J_Int_J_Array;
   pragma Export (C, AdaString_Id_JNI_448, "Java_adarecord_Standard_AdaString_AdaString_1Id_1JNI_1448__Ljava_lang_String_2");

   Id_JNI_246 : AJIS.Internal.Java.Java_Method_Access := AJIS.Internal.Java.Get_Java_Method ("adarecord/Standard/AdaString", "<init>", "(Lcom/adacore/ajis/internal/ada/AdaAccess;)V");

end JNI_Binding.Standard_JNI.AdaString_JNI;
