/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2014 (20140331))          *
 * Original Ada unit: Ada2Java                                               *
 * Generation timestamp: 201412281256                                        *
 *****************************************************************************/

package quiz.Ada2Java;

/**
 */
@SuppressWarnings("all")
public final class Library {
   public static final com.adacore.ajis.ILock lock = new com.adacore.ajis.DefaultLock ();
   private static boolean fLoaded = false;

   private static native void startLibrary ();

   public static void load () {
      if (!fLoaded) {
         fLoaded = true;
         com.adacore.ajis.AJISLibrary.load ();
         System.loadLibrary ("quiz");
         startLibrary ();
      }
   }

   static {
      quiz.Ada2Java.Library Id_JNI_395;
      quiz.Ada.Exceptions.Exception_Occurrence Id_JNI_396;
      quiz.Q4.Q4_Package Id_JNI_397;
      quiz.Q4.Target Id_JNI_398;
      quiz.Standard.AdaString Id_JNI_399;
      quiz.Standard.Constraint_Error Id_JNI_400;
      quiz.Standard.Program_Error Id_JNI_401;
      quiz.Standard.Storage_Error Id_JNI_402;
   }

   static {
      quiz.Ada2Java.Library.load ();
   }

} // Library
